INT-4118: Detect EOF on stdin
spring-projects/spring-integration pull request #1900
Opened 2016-09-22 15:58 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4118

Add an option to the `CharacterStreamReadingMessageSource` to detect EOF
on the stream and close the context.

2016-09-26 19:28 UTC, artembilan commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +						context.close();
I don't like this.

Maybe `EndOfStreamEvent` and then an application will be free to chose what do to with the fact. 
Close `ctx`, just stop adapters or switch to another stream.
Anything possible, but not just aggressive unconditional `ctx.close()` .

I won't mind if you have enough arguments to stay with this solution.
Thanks

2016-09-26 19:29 UTC, artembilan commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +	 * @return the stream.
`@since 5.0`

2016-09-26 19:30 UTC, artembilan commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +	 * @return the stream.
`@since 5.0`

2016-09-26 19:32 UTC, artembilan requested changes

2016-09-26 20:27 UTC, garyrussell commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +						context.close();
Yes, good idea - in fact the OP on Stack Overflow came to the same conclusion.

2016-10-05 18:28 UTC, artembilan requested changes

2016-10-05 18:28 UTC, artembilan commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +	 * Construct an instance with the provider reader and buffer size.
Typo: provide**d**

2016-10-05 18:28 UTC, artembilan commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +	 * When {@code blockReceive} is {@code false},
There is no such a `blockReceive` argument any more.

2016-10-05 18:28 UTC, artembilan commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +	 * underlying stream is closed, the application context (if present) will be closed.
Wrong behavior description. 
Need to be changed to the published event.

2016-10-05 18:28 UTC, artembilan commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +					this.eventPublished = true;
I'm not sure in this `eventPublished` state.
As for me that looks natural to receive `StreamClosedEvent` whenever I call this `receive()`. 
Any call to closed stream should be ended with the same result.
In our case it is an `ApplicationEvent`.
WDYT?

2016-10-05 18:28 UTC, artembilan commented on spring-integration-stream/src/main/resources/org/springframework/integration/stream/config/spring-integration-stream-5.0.xsd
> +						When 'true' the an application event is published when EOF is detected
Typo:  ~~the~~ an application

2016-10-05 18:28 UTC, artembilan commented on spring-integration-stream/src/test/java/org/springframework/integration/stream/CharacterStreamSourceTests.java
> +		verify(publisher).publishEvent(any(ApplicationEvent.class));
M-m-m. Doesn't it work for the particular `StreamClosedEvent` type?

2016-10-05 18:28 UTC, artembilan commented on src/reference/asciidoc/whats-new.adoc
> +There is a new option on the `CharacterStreamReadingMessageSource` to allow it to be used to "pipe" stdin and close the application context when the pipe is closed.
That's not true anymore.

2016-10-05 18:49 UTC, garyrussell commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +					this.eventPublished = true;
I was just concerned that we'd keep publishing on every poll - while that might be ok in the case when the user decides to stop the app but if he keeps going it is unnecessary overhead.

I don't mind either way; WDYT?

2016-10-05 18:51 UTC, garyrussell commented on spring-integration-stream/src/test/java/org/springframework/integration/stream/CharacterStreamSourceTests.java
> +		verify(publisher).publishEvent(any(ApplicationEvent.class));
See the mockito java docs - it doesn't check the type, athough it may do in future.

I'll change it.

2016-10-05 18:57 UTC, garyrussell commented on spring-integration-stream/src/main/java/org/springframework/integration/stream/CharacterStreamReadingMessageSource.java
> +					this.eventPublished = true;
Agreed - will push another commit soon

2016-10-05 23:29 UTC, artembilan requested changes
Well, a couple typos.
Will fix on merge...

2016-10-05 23:29 UTC, artembilan commented on src/reference/asciidoc/stream.adoc
> +NOTE: To faciltate EOF detection, the poller thread will block in the `receive()` method until either data arrives or EOF is detected.
Typo: facil**i**tate

2016-10-05 23:29 UTC, artembilan commented on src/reference/asciidoc/stream.adoc
> +If you intend to perform some interruptible task after stopping the adapter, you must either perform the `stop()` on a different thread, or use a differnent thread for those downstrean activities.
Two typos: 
differ~~n~~ent
downstrea~~n~~**m**

2016-10-05 23:32 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/f9ddefec2cca10bb8f1a0d030cb1aacf79b140e8

2016-10-05 23:32 UTC, closed without merging