INT-3770: Add TX support from mid-flow
spring-projects/spring-integration pull request #1960
Opened 2016-11-02 23:32 UTC by artembilan

JIRA: https://jira.spring.io/browse/INT-3770

Having `TransactionHandleMessageAdvice` we can start TX from any `MessageHandler.handleMessage()`

* Add `<transactional>` alongside with the `<request-handler-advice-chain>` for those components which produce reply
* Merge `<transactional>` and `<request-handler-advice-chain>` configuration to a single `ManagedList`
* Rework JPA `<transactional>` in favor of common solution
* Some polishing and refactoring

2016-11-04 16:53 UTC, garyrussell requested changes

2016-11-04 16:53 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/endpoint/AbstractPollingEndpoint.java
> +		List<Advice> receiveOnlyAdviceChain = new ArrayList<>();
`... = null`

Directly assign result of `collect()` and add else clause to set as `ArrayList<>()`.

2016-11-04 16:53 UTC, garyrussell commented on spring-integration-core/src/test/java/org/springframework/integration/config/AggregatorParserTests-context.xml
> +			<expire-transactional/>
Hmmm - someone might have applied some other advice here.

2016-11-04 17:06 UTC, artembilan commented on spring-integration-core/src/test/java/org/springframework/integration/config/AggregatorParserTests-context.xml
> +			<expire-transactional/>
??? Not sure in your question.
This functionality hasn't been changed. 
The `<expire-advice-chain/>` still exists. I just didn't want to write some class for mock `Advice` and just used `transactionManager` on the matter. 
The issue with test that it checks `adviceChain` presence, but now we don't populate empty `adviceChain`.

Am I missing anything else ?

2016-11-07 14:04 UTC, garyrussell commented on spring-integration-core/src/test/java/org/springframework/integration/config/AggregatorParserTests-context.xml
> +			<expire-transactional/>
Doh - brain fart - I must have thought we were still in the schema above 😄

2016-11-07 14:05 UTC, garyrussell approved these changes

2016-11-07 14:07 UTC, garyrussell commented
Merged as 5cca8e8e018c3a5dac4315b81b4ffce6cd01bfc3

2016-11-07 14:07 UTC, closed without merging