INT-4154: Merge Files Java DSL
spring-projects/spring-integration pull request #1963
Opened 2016-11-04 20:24 UTC by artembilan

JIRA: https://jira.spring.io/browse/INT-4154

* Move `Transformers` for files to the `Files` factory
* Remove `@Deprecated` methods
* Fix `FilesTests` for new packages and removed methods like `.handleWithAdapter()`

2016-11-10 19:30 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/FileTransferringMessageHandlerSpec.java
> + *
Javadoc

2016-11-10 19:30 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/FileWritingMessageHandlerSpec.java
> + * @author Artem Bilan
Javadoc

2016-11-10 19:35 UTC, garyrussell requested changes
We should at least address the class-level javadocs and at a minimum open a cleanup JIRA for the others.

2016-11-10 19:35 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/FileWritingMessageHandlerSpec.java
> +	 */
We're a bit inconsistent here with some methods having Javadoc, others not (and none in the previous spec).

I am not saying we have to address it now, but we should make sure when we do docs for RC/GA that we addres these too.

2016-11-10 19:35 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/RemoteFileOutboundGatewaySpec.java
> + *
Javadoc

2016-11-10 19:35 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/RemoteFileOutboundGatewaySpec.java
> +	public S localDirectoryExpression(Expression localDirectoryExpression) {
again, consistency

2016-11-10 19:37 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/RemoteFileOutboundGatewaySpec.java
> +	public S localDirectoryExpression(Expression localDirectoryExpression) {
Np. I'm on it.
Addressing all the missed JavaDocs in these DSL classes for File module...

2016-11-10 22:21 UTC, artembilan commented
Doing this I noticed that we are missing `srteaming` adapters DSL.

If you wish I can provide provide a base `Spec` class here in the File `dsl` package or you can extract it during (S)FTP work.

Works for me any way.

2016-11-11 15:06 UTC, garyrussell commented
I will take care of the streaming stuff while doing (S)FTP.

2016-11-11 15:15 UTC, garyrussell approved these changes

2016-11-11 15:17 UTC, garyrussell commented
Merged as f71d6a0e66887eba75ad4dd634b3220c6aa74d0e

2016-11-11 15:17 UTC, closed without merging