INT-4155: Port FTP DSL
spring-projects/spring-integration pull request #1975
Opened 2016-11-11 19:33 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4155

- Add streaming support
- Rework tests to use dynamic flow registrations due to the test FTP server is now a test support class.

__FTP only - I will wait for review/polishing before pushing SFTP - either as a new commit here, or a new PR__

2016-11-11 21:16 UTC, artembilan requested changes
Will take a look more in the evening.
But at least it is something to consider.

2016-11-11 21:16 UTC, artembilan commented on spring-integration-ftp/src/main/java/org/springframework/integration/ftp/dsl/Ftp.java
> + * @author Gary Russell
`@since 5.0`

2016-11-11 21:16 UTC, artembilan commented on spring-integration-ftp/src/test/java/org/springframework/integration/ftp/dsl/FtpTests.java
> +	@IntegrationComponentScan
I think this is redundant.

2016-11-11 21:32 UTC, artembilan requested changes
That's all.
I think you can go ahead with the SFTP.

2016-11-11 21:32 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/RemoteFileStreamingInboundChannelAdapterSpec.java
> +	 * @param remoteDirectory The remote directory expression.
Typo: remoteDirectoryExpression

2016-11-11 21:32 UTC, artembilan commented on spring-integration-ftp/src/main/java/org/springframework/integration/ftp/dsl/Ftp.java
> +	 * @param sessionFactory the session factory.
Wrong param. Must be `remoteFileTemplate`

2016-11-11 21:32 UTC, artembilan commented on spring-integration-ftp/src/main/java/org/springframework/integration/ftp/dsl/Ftp.java
> +	 * @param sessionFactory the session factory.
Wrong param. Must be `remoteFileTemplate`

2016-11-12 14:45 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/RemoteFileStreamingInboundChannelAdapterSpec.java
> +	public S remoteDirectory(Function<Message<?>, String> remoteDirectoryFunction){
I don't understand why, but my local `./gradlew check` didn't find this.

2016-11-12 14:50 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/dsl/RemoteFileStreamingInboundChannelAdapterSpec.java
> +	public S remoteDirectory(Function<Message<?>, String> remoteDirectoryFunction){
Doh - I only ran `:spring-integration-ftp:check`.

2016-11-14 15:12 UTC, artembilan approved these changes
Nothing to complain about.
I can merge or can wait for SFTP part.

2016-11-14 18:23 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/8070f72c445b52eff1f1aacd8e3be8ed31de6b43

2016-11-14 18:23 UTC, closed without merging