INT-4158: Port Java DSL for JPA module
spring-projects/spring-integration pull request #1976
Opened 2016-11-14 18:15 UTC by artembilan

JIRA: https://jira.spring.io/browse/INT-4158

* Add JavaDocs
* De-Boot `JpaDslTests`
* Fix typos and generics inconsistency in the `JpaOutboundGatewayFactoryBean`

2016-11-15 18:07 UTC, garyrussell requested changes
That's all; minor.

2016-11-15 18:07 UTC, garyrussell commented on spring-integration-jpa/src/test/java/org/springframework/integration/jpa/dsl/JpaDslTests.java
> +public class JpaDslTests {
`Dsl` is redundant - however, I can see it's useful to have it in the class name - I haven't been renaming these tests in the modules I ported; perhaps we should be consistent either way.

2016-11-15 18:23 UTC, artembilan commented on spring-integration-jpa/src/test/java/org/springframework/integration/jpa/dsl/JpaDslTests.java
> +public class JpaDslTests {
Yeah! Not a question. 
I just was a bit paranoiac that the name like `JpaTests`  doesn't say so much about the purpose of the test. Although maybe `.dsl` package does the trick...

Will rename for consistency.

2016-11-15 18:33 UTC, garyrussell commented on spring-integration-jpa/src/main/java/org/springframework/integration/jpa/dsl/JpaBaseOutboundEndpointSpec.java
> +		*/
Got it - ok; let's leave it like this.

2016-11-17 19:30 UTC, garyrussell approved these changes

2016-11-17 19:31 UTC, garyrussell commented
Merged as 1bba73fc060faec6141e2edd957c98ad6a56615c

2016-11-17 19:31 UTC, closed without merging