Add an option to skip StdErr process if it is not needed
spring-projects/spring-integration pull request #2006
Opened 2016-12-16 13:41 UTC by shahbour

based on INT-4187 and my question in [stack overflow ](http://stackoverflow.com/questions/41075112/file-tail-inbound-channel-adapter-stderr-and-stdout) . I did name the new field enableStatusReader per function name .

This is my first contribution so if i did any thing wrong please tell me

2016-12-16 14:13 UTC, shahbour commented
i did not change any thing in spring-integration-scripting but it failed

> Execution failed for task ':spring-integration-scripting:test'.

2016-12-16 15:55 UTC, garyrussell commented
@shahbour Looks good; thanks for the contribution!

We should add javadocs to the new setter methods; we also need to confirm the parser change with an update to `FileTailInboundChannelAdapterParserTests` to verify the boolean is reset when so configured.

If you don't have time to address these; let us know and we'll take of it during the merge.

2016-12-16 16:57 UTC, shahbour commented
It's ok I'll do that

Thanks

On Dec 16, 2016 5:55 PM, "Gary Russell" <notifications@github.com> wrote:

> @shahbour <https://github.com/shahbour> Looks good; thanks for the
> contribution!
>
> We should add javadocs to the new setter methods; we also need to confirm
> the parser change with an update to FileTailInboundChannelAdapterP
> arserTests to verify the boolean is reset when so configured.
>
> If you don't have time to address these; let us know and we'll take of it
> during the merge.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/spring-projects/spring-integration/pull/2006#issuecomment-267625267>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABzk-BbypPnMOSMMteadE6C-PVxnag3Pks5rIrRfgaJpZM4LPMiL>
> .
>

2016-12-16 19:18 UTC, shahbour commented
@garyrussell i did the updated , but i am not sure this is what you mean in tests , if you don't mind elaborate more

2016-12-16 19:26 UTC, garyrussell commented
Thanks, it's close, but that's just testing the default value (true) - i.e. tests that the parser doesn't change the default when not specified, which is a good test; but we also need a test for explicitly setting it to false in the test case's XML config and then verify it's false in the bean.

2016-12-16 19:30 UTC, artembilan requested changes
Would be great to have some note in the Reference Manual as well.
Thank you for the prompt contribution!

2016-12-16 19:30 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/config/FileTailInboundChannelAdapterFactoryBean.java
> +	 * @param enableStatusReader true or false
Add `@since 5.0`.
Although if you decided with @garyrussell to backport the fix to `4.3.x`, the version must be `4.3.6`

2016-12-16 19:30 UTC, artembilan commented on spring-integration-file/src/test/java/org/springframework/integration/file/config/FileTailInboundChannelAdapterParserTests.java
> +		assertTrue(TestUtils.getPropertyValue(nativeAdapter, "enableStatusReader" ,Boolean.class));
OK. 
Now let's make make a test for `assertFalse()`.
I mean we should be sure that changes to the parser reflects to the target `OSDelegatingFileTailingMessageProducer`.

What I want to say that it isn't possible now.
You should add `enable-status-reader` XSD attribute and modify `FileTailInboundChannelAdapterParserTests-context.xml` with `enable-status-reader="false"`

2016-12-16 19:31 UTC, artembilan commented
Also pay attention to the CheckStyle failures:
```
FileTailInboundChannelAdapterParserTests.java:98:90: ',' is preceded with whitespace. [NoWhitespaceBefore]

[ant:checkstyle] [ERROR] /home/travis/build/spring-projects/spring-integration/spring-integration-file/src/test/java/org/springframework/integration/file/config/FileTailInboundChannelAdapterParserTests.java:98:92: ',' is not followed by whitespace. [WhitespaceAfter]
```
For this purpose you can locally run `check` Gradle command instead of just `test`.

2016-12-16 19:33 UTC, garyrussell commented
I think this can be backported so `@since 4.3.6` is correct.

Also note the checkstyle failure in travis.

You can run checkstyle locally with 

    ./gradlew :spring-integration-file:check

2016-12-16 19:39 UTC, shahbour commented
Thanks guys for the support, as I am new to tests it might take a while
with me , but I am looking forward to do it.

On Dec 16, 2016 9:33 PM, "Gary Russell" <notifications@github.com> wrote:

> I think this can be backported so @since 4.3.6 is correct.
>
> Also note the checkstyle failure in travis.
>
> You can run checkstyle locally with
>
> ./gradlew :spring-integration-file:check
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/spring-projects/spring-integration/pull/2006#issuecomment-267677279>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABzk-Efnv48KDPgxSgknT3caN8Q6hW9cks5rIueVgaJpZM4LPMiL>
> .
>

2016-12-16 20:10 UTC, artembilan commented
@shahbour , please, don't hesitate to ask questions on the matter.

Also, please, add `@DirtiesContex` for the `FileTailInboundChannelAdapterParserTests`.
There are several adapters with the `auto-startup="true"` meaning that they start with the context and spawn threads. By default `@RunWith(SpringJUnit4ClassRunner.class)` doesn't close application context for caching reasons in between test classes. In Spring Integration we don't need that feature, but we should be sure that all processes are destroyed after test class. Therefore `@DirtiesContex`. See it's JavaDoc.

2016-12-17 09:08 UTC, shahbour commented
how can i add note to the Reference Manual

2016-12-19 20:24 UTC, artembilan approved these changes

2016-12-19 20:24 UTC, artembilan commented on src/reference/asciidoc/file.adoc
> +You can discard the standard error events by setting enable-status-reader to false.
Need to wrap attribute to the code formatting, but that is minor. Will fix on merge.
LGTM

Also need `TailAdapterSpec` modification for Java DSL.
Plus I don't see any sample in the doc.
All this work is for another pull request.

Feel free to consider that part as a subsequent contribution as well, @shahbour 😄

2016-12-19 20:41 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/16c7535577a1cd38681188b0194ad2d8c8cbb684 and cherry-picked.

@shahbour , 
thank you for contribution.
Looking forward for more!

2016-12-19 20:41 UTC, closed without merging