INT-4195: More Aggregator Performance Improvements
spring-projects/spring-integration pull request #2010
Opened 2016-12-22 22:45 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4195

Avoid the N^2 search in `SequenceAwareMessageGroup` when the group is a
`SimpleMessageGroup`.
Avoid the use of the header accessor if the N^2 search is needed (SPR-15045).

__cherry-pick to 4.3.x__

2016-12-22 23:23 UTC, artembilan requested changes
All minor.
I can address on merge.
Jut let me know!

2016-12-22 23:23 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/aggregator/AbstractCorrelatingMessageHandler.java
> +						IntegrationMessageHeaderAccessor.SEQUENCE_NUMBER);
Yes, I thought not one time that use extra object to just get friendly accessor to the value isn't good idea at all...
Let's don't use it in the `canAdd()` as well !

Anyway why `member.getHeaders().get(IntegrationMessageHeaderAccessor.SEQUENCE_NUMBER, Integer.class)` doesn't work for you here?
Looks like pretty parallel with what you do manually with this `if..else`

2016-12-22 23:23 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/store/SimpleMessageGroup.java
> +		if (sequence instanceof Integer) {
M-m-m. I think that should be fine just to request only `Integer` type for the header, like it is done right now via `messageHeaderAccessor.getSequenceNumber()`.
I mean we should just do this directly without any `if`:
```
Integer sequence = message.getHeaders().get(IntegrationMessageHeaderAccessor.SEQUENCE_NUMBER, Integer.class);
this.sequences.add(sequence != null ? sequence : 0);
```
and that's all

2016-12-22 23:23 UTC, artembilan commented on spring-integration-core/src/test/java/org/springframework/integration/aggregator/AggregatorTests.java
> +		assertThat(stopwatch.getTotalTimeSeconds(), lessThan(60.0)); // actually < 2.0, was many minutes
Well, I have given up already after:
```
2016-12-22 18:18:43,198 WARN AggregatorTests [main] : Sent 10000 in 26.661 (10k in 26661ms)
2016-12-22 18:20:01,117 WARN AggregatorTests [main] : Sent 20000 in 104.58 (10k in 77919ms)
```
😄

2016-12-22 23:33 UTC, artembilan commented
H-m.
That fully unclear to me what's wrong with that MongoDB test on Travis.
There is no any race condition. Only I can guess that didn't have connect to the MongoDB during TX commit.
Different story though...

2016-12-23 14:16 UTC, artembilan commented
LGTM.
Although WDYT about many other `new IntegrationMessageHeaderAccessor()` usage?
Wouldn't it be better to get rid of them as well?
Thanks

2016-12-23 14:23 UTC, garyrussell commented
I don't think it's such a big issue once Spring is fixed.

2016-12-23 14:36 UTC, artembilan approved these changes

2016-12-23 14:39 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/a466579ee1e9b3a846373a53a9b5ce20a921294d and cherry-picked.

2016-12-23 14:39 UTC, closed without merging