INT-4198: TCP: Add Hook to Customize SSLEngine
spring-projects/spring-integration pull request #2013
Opened 2016-12-28 20:18 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4198

Enable setting properties like `needClientAuth` on the `SSLEngine` - when not using
NIO, this can be set on the server socket with a socket support implementation.

Add `nio-connection-support` to namespace.

Improved "Advanced Techniques" documentation, using this use case as an example.

Fail fast with NIO when SSL handshaking fails.

__cherry-pick to 4.3.x__

2016-12-28 23:40 UTC, artembilan requested changes
Looks like that's all.
Nothing critical!

2016-12-28 23:40 UTC, artembilan commented on spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/connection/DefaultTcpNioSSLConnectionSupport.java
>  		this.sslContext = this.sslContextSupport.getSSLContext();
Not related to this fix, but can't we get rid of this extra `InitializingBean` operation and just `getSSLContext()` directly in the ctor ?

2016-12-28 23:40 UTC, artembilan commented on spring-integration-ip/src/test/java/org/springframework/integration/ip/tcp/connection/SocketSupportTests.java
> +			// NOSONAR
Don't we need to have some assertion here?

2016-12-28 23:40 UTC, artembilan commented on spring-integration-ip/src/test/java/org/springframework/integration/ip/tcp/connection/SocketSupportTests.java
> +				((SSLServerSocket) serverSocket).setNeedClientAuth(true);
I wonder what is the default behavior?
Who makes auth?

Thanks

2016-12-28 23:40 UTC, artembilan commented on spring-integration-ip/src/test/java/org/springframework/integration/ip/tcp/connection/SocketSupportTests.java
> +		};
The `DefaultTcpSSLContextSupport` isn't `abstract`.
Why do we need this empty extension?

2016-12-29 15:32 UTC, garyrussell commented on spring-integration-ip/src/test/java/org/springframework/integration/ip/tcp/connection/SocketSupportTests.java
> +				((SSLServerSocket) serverSocket).setNeedClientAuth(true);
By default, only the server certificate is checked. Client auth is either not required, requested (optional) or required. See [the javadocs](https://docs.oracle.com/javase/8/docs/api/javax/net/ssl/SSLSocket.html#setNeedClientAuth-boolean-).

2016-12-29 16:16 UTC, garyrussell commented on spring-integration-ip/src/test/java/org/springframework/integration/ip/tcp/connection/SocketSupportTests.java
> +			// NOSONAR
There's a race and two exceptions are possible - I will add code.

2016-12-29 16:36 UTC, garyrussell commented
Pushed - the multi-catch will have to be split after cherry-picking.

Also, the deprecated `afterPropertiesSet()` could be removed on master (but not 4.3.x).

2016-12-29 18:15 UTC, artembilan approved these changes

2016-12-29 18:42 UTC, artembilan commented on spring-integration-ip/src/test/java/org/springframework/integration/ip/tcp/connection/SocketSupportTests.java
> +		catch (SSLHandshakeException e) {
This passes for me or fails sporadically 😢.
With the :
```
java.net.SocketException: Software caused connection abort: recv failed

	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.waitForClose(SSLSocketImpl.java:1769)
	at sun.security.ssl.HandshakeOutStream.flush(HandshakeOutStream.java:124)
	at sun.security.ssl.Handshaker.sendChangeCipherSpec(Handshaker.java:1083)
	at sun.security.ssl.ClientHandshaker.sendChangeCipherAndFinish(ClientHandshaker.java:1222)
	at sun.security.ssl.ClientHandshaker.serverHelloDone(ClientHandshaker.java:1134)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:348)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.springframework.integration.ip.tcp.connection.TcpNetConnection.send(TcpNetConnection.java:107)
	at org.springframework.integration.ip.tcp.connection.SocketSupportTests.testNetClientAndServerSSLDifferentContexts(SocketSupportTests.java:361)
	at org.springframework.integration.ip.tcp.connection.SocketSupportTests.testNetClientAndServerSSLDifferentContexts(SocketSupportTests.java:315)
```
or 
```
javax.net.ssl.SSLException: java.net.SocketException: Software caused connection abort: recv failed

	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1870)
	at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1815)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:116)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:71)
	at org.springframework.integration.ip.tcp.serializer.ByteArrayCrLfSerializer.fillToCrLf(ByteArrayCrLfSerializer.java:60)
	at org.springframework.integration.ip.tcp.serializer.ByteArrayCrLfSerializer.doDeserialize(ByteArrayCrLfSerializer.java:48)
	at org.springframework.integration.ip.tcp.serializer.AbstractPooledBufferByteArraySerializer.deserialize(AbstractPooledBufferByteArraySerializer.java:82)
	at org.springframework.integration.ip.tcp.serializer.AbstractPooledBufferByteArraySerializer.deserialize(AbstractPooledBufferByteArraySerializer.java:34)
	at org.springframework.integration.ip.tcp.connection.TcpNetConnection.getPayload(TcpNetConnection.java:121)
	at org.springframework.integration.ip.tcp.connection.TcpMessageMapper.toMessage(TcpMessageMapper.java:154)
	at org.springframework.integration.ip.tcp.connection.TcpNetConnection.run(TcpNetConnection.java:165)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
```
Yes, on Windows.
I wonder if we still have some race condition somewhere ...

2016-12-29 20:31 UTC, garyrussell commented on spring-integration-ip/src/test/java/org/springframework/integration/ip/tcp/connection/SocketSupportTests.java
> +		catch (SSLHandshakeException e) {
Yes, but it's buried in SSL somewhere.

2016-12-29 23:16 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/a0f0b6ab64cf2d421d64ed6837dd609fc12fbc5b and cherry-picked as https://github.com/spring-projects/spring-integration/commit/6cd0845cfa7644563256ee5def01c13f188cc021

2016-12-29 23:16 UTC, closed without merging