INT-4204: Introduce `ExpressionFileListFilter`
spring-projects/spring-integration pull request #2033
Opened 2017-01-16 14:55 UTC by artembilan

JIRA: https://jira.spring.io/browse/INT-4204

2017-01-18 20:41 UTC, garyrussell requested changes

2017-01-18 20:41 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/ExpressionFileListFilter.java
> +public class ExpressionFileListFilter<F> extends AbstractFileListFilter<F>
Given that SpEL is not type safe, and we don't need subclasses, should this be generic?

    public class ExpressionFileListFilter extends AbstractFileListFilter<Object>

?

2017-01-18 21:07 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/ExpressionFileListFilter.java
> +public class ExpressionFileListFilter<F> extends AbstractFileListFilter<F>
Well, we could, indeed but then we can't use `AbstractInboundFileSynchronizer.setFilter(FileListFilter<F> filter)` as is.
We have to go through all the casting hell.

2017-01-18 21:25 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/ExpressionFileListFilter.java
> +public class ExpressionFileListFilter<F> extends AbstractFileListFilter<F>
👍

2017-01-19 21:27 UTC, garyrussell approved these changes

2017-01-19 21:31 UTC, garyrussell commented
Merged as 9836828f54def6e3276b3370d8e2dab9f9788020

2017-01-19 21:31 UTC, closed without merging