INT-4227: Allow custom Messaging Annotations
spring-projects/spring-integration pull request #2052
Opened 2017-02-13 20:07 UTC by artembilan

JIRA: https://jira.spring.io/browse/INT-4227

Expose `MessagingAnnotationPostProcessor` for inheritors.
The `CustomMessagingAnnotationTests` demonstrates how custom Messaging Annotation can be registered and used

**Cherry-pick to 4.3.x**

2017-02-15 18:27 UTC, garyrussell requested changes

2017-02-15 18:27 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/config/annotation/MessagingAnnotationPostProcessor.java
`// NOSONAR` on each.

2017-02-15 18:27 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/config/annotation/MessagingAnnotationPostProcessor.java
However, I think I'd prefer `protected void addPostProcessor(...)` etc, rather than exposing the internals.

2017-02-15 18:27 UTC, garyrussell commented on spring-integration-core/src/test/java/org/springframework/integration/config/annotation/CustomMessagingAnnotationTests.java
> +		org.apache.commons.logging.Log log =
Why not change the interface name to avoid this FQCN noise?

2017-02-15 18:53 UTC, artembilan commented
How about this?

There is another idea like request all those `MethodAnnotationPostProcessor` from `BeanFactory` as beans and don't mess with the `MessagingAnnotationPostProcessor` override or explicit declaration at all.

But that requires some breaking changes for the `AbstractMethodAnnotationPostProcessor` design.

OTOH the `MessagingAnnotationPostProcessor` is `BPP` and it might really be better do not interfere `BeanFactory` from that level and just let end-user to override the bean on its own purpose...

2017-02-15 19:04 UTC, garyrussell commented
I think this technique is fine.

However, perhaps we should break `pPAI` into smaller chunks and make most methods protected?

2017-02-15 19:15 UTC, artembilan commented
> perhaps we should break pPAI into smaller chunks and make most methods protected?

M-m-m. Would you mind to elaborate more? Some simple sample what to change and how.
Thanks

2017-02-15 19:49 UTC, garyrussell commented
I am not exactly sure but, let's say someone wants to "enhance" (e.g. synthesize) an annotation.

e.g. Annotation `@Foo` meta-annotated with `@ServiceActivator` and they want to set some attributes on SA.

Currently there's no way to do that.

If we make `getAnnotationChain()` protected, the user could do it there.

Also, as we iterate over the `annotationChains.keySet()`, if the body of the for loop was a protected method, the subclass could take some different action in some cases, and call `super` in others.

2017-02-15 19:56 UTC, artembilan commented
OK!

I'll take a look into that.
Thanks

2017-02-24 15:38 UTC, garyrussell approved these changes

2017-02-24 15:49 UTC, garyrussell commented
Merged as 693adfd774a2c81734573681b620845a96a7696f 

Cherry-pick conflicts with https://github.com/spring-projects/spring-integration/commit/868004e9e4194f59820427fe1db3d44fbb67596c

It's probably easiest for you to fix and create a new PR for the back port. thx

2017-02-24 16:32 UTC, artembilan commented
Backport PR #2069

2017-02-24 16:32 UTC, closed without merging