INT-4219: Add @UseSpelInvoker [REVIEW ONLY - PoC]
spring-projects/spring-integration pull request #2076
Opened 2017-03-01 23:13 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4219

Needs (a lot) more work, tests, docs.

Just want to get buy-in for the approach.

Also see note about resolving placeholders for compiler mode.

2017-03-02 17:08 UTC, artembilan requested changes
I we're good to go with this approach and that doesn't look so ugly if you don't like to use `InvocableMessageHandler`.

I don't see how you apply that `compilerMode`, but I guess that willl in upcoming commits.

2017-03-02 19:17 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/config/annotation/AbstractMethodAnnotationPostProcessor.java
> +		return this.beanFactory;
Yeah - this is some left-over dross from when I was trying to use the BF too early.

2017-03-02 20:36 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/annotation/UseSpelInvoker.java
> +public @interface UseSpelInvoker {
I don't think so; we will need that for XML config (either a new attribute or they can autowire the handler and set the flag).

2017-03-02 20:43 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/annotation/UseSpelInvoker.java
> +public @interface UseSpelInvoker {
??? Even for XML config the POJO method can be marked with the `@UseSpelInvoker`.
We don't prohibit to use `@ServiceActivator` and similar when we parse XML config.
Finally everything ends up in the `MessagingMethodInvokerHelper` which just reads a `Method` for particular options and generates SpEL and `InvocableHandlerMethod` for runtime.

2017-03-02 21:04 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/annotation/UseSpelInvoker.java
> +public @interface UseSpelInvoker {
The problem is they might want to invoke a class/method they don't own and can't annotate.

2017-03-02 21:07 UTC, garyrussell commented
Next iteration.

2017-03-02 22:05 UTC, artembilan commented
Well, I think the progress is good here.
You can go ahead what you want to do here else.

And I see your point about an external class to use from XML.
There is always a workaround like local wrapper around that remote method.
My point just don't spend time for XML effort.
At least until strong requirements.

2017-03-02 22:06 UTC, garyrussell commented
>My point just don't spend time for XML effort.

Agreed.

2017-03-02 22:42 UTC, artembilan commented
FYI: there are some failures according Travis report.

2017-03-03 19:43 UTC, artembilan commented
Well, looks like we need only docs on the matter already!
And resolving conflicts after rebase.
Do you have anything else in mind to do for this task ?

2017-03-03 20:44 UTC, garyrussell commented
PR soon (tests and docs) - doing a `testAll` right now 😄

2017-03-04 01:09 UTC, artembilan approved these changes
A couple (in fact one) typos.
Merging...

2017-03-04 01:09 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/annotation/UseSpelInvoker.java
> +	 * mode will be used. Must evaluate to a String containing a valide compiler mode.
Typo: valid

Will fix on merge

2017-03-04 01:09 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/annotation/UseSpelInvoker.java
> +	 * mode will be used. Must evaluate to a String containing a valide compiler mode.
DITO.
Copy/paste artefact 😄

2017-03-04 01:13 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/a50d866f81888f27c56f7298d946b786c52e9281

2017-03-04 01:13 UTC, closed without merging