#2110 Refactor MessageGroupMetadata to be compatible with Jackson serialization
spring-projects/spring-integration pull request #2112
Opened 2017-04-06 11:24 UTC by urgelacko

2017-04-06 11:24 UTC, pivotal-issuemaster commented
@urgelacko Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2112)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2112) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2017-04-06 11:25 UTC, pivotal-issuemaster commented
@urgelacko Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2112)!

2017-04-06 18:22 UTC, artembilan requested changes

2017-04-06 18:22 UTC, artembilan commented on spring-integration-core/src/test/java/org/springframework/integration/store/MessageGroupMetadataJacksonTest.java
> +public class MessageGroupMetadataJacksonTest {
OK, @urgelacko ,

that's great contribution!

Would you mind to add JSON-based test for the `RedisMessageStore`?
As far as that one was the reason to come here with the concerns

Thank you!

2017-04-07 13:02 UTC, urgelacko commented on spring-integration-core/src/test/java/org/springframework/integration/store/MessageGroupMetadataJacksonTest.java
> +public class MessageGroupMetadataJacksonTest {
Yes, I will try to add it soon.
Thanks!

2017-05-02 17:36 UTC, artembilan commented
@urgelacko ,

I have reviewed this ad realized that the situation is much complicated than just `MessageGroupMetadata`.
I've gone ahead and implemented this #2138 .

I used your fix for the `MessageGroupMetadata` and followed with similar way in some other places.
Since that PR covers this change as well, we are closing this one.

Your feedback in that PR is much than welcome.

And thank you for the contribution!

2017-05-02 17:36 UTC, closed without merging

2017-05-10 11:40 UTC, urgelacko commented
@artembilan 
Sorry for disappearing but recently I had zero time to implement this. Thank you for finishing and adding this to SI.
Bests