INT-4265: Add Java DSL .routeByError() EIP-method
spring-projects/spring-integration pull request #2136
Opened 2017-04-26 23:11 UTC by artembilan

JIRA: https://jira.spring.io/browse/INT-4265

* Add `.routeByError()` EIP-method to the `IntegrationFlowDefinition`
based on the `ErrorMessageExceptionTypeRouter`
* Add missed `dynamicChannelLimit()` option to the `RouterSpec`
* Rework `RouterSpec#RouterMappingProvider` into the `ContextRefreshedEvent`
phase initialization to be sure that dependent `MappingMessageRouterManagement`
is fully initialized before applying mapping conversions

2017-05-01 18:34 UTC, garyrussell requested changes

2017-05-01 18:34 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/RouterSpec.java
> +		public void onApplicationEvent(ContextRefreshedEvent event) {
Shouldn't we confirm that the event context is this bean's declaring context?

2017-05-01 18:34 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/IntegrationFlowDefinition.java
> +	public B routeByError(
Perhaps `routeByThrowable` would be more correct?

The javadocs for `ErrorMessageExceptionTypeRouter` are incorrect too (`Exception` Vs. `Throwable`).

2017-05-01 18:39 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/IntegrationFlowDefinition.java
> +	public B routeByError(
Well, `ErrorMessage` accepts `Throwable`, too...
We don't pursue here the strong alignment with types we use. Just human-friendly is enough, IMO...

2017-05-01 18:40 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/RouterSpec.java
> +		public void onApplicationEvent(ContextRefreshedEvent event) {
I think so. Will fix.
Thanks

2017-05-01 18:46 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/IntegrationFlowDefinition.java
> +	public B routeByError(
I agree, but specifically, here (and in the EMTR), we are routing on a `Throwable` payload, not an `ErrorMessage`.

2017-05-01 18:46 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/IntegrationFlowDefinition.java
> +	public B routeByError(
`Error` has a meaning in Java and we shouldn't mislead.

2017-05-01 19:40 UTC, artembilan commented
Pushed. But I renamed it into `routeByException` . Somehow I don't feel comfort with all those `.able()` in the public method API names...
If you insist, I'll rename to the `routeByThrowable()`. That is just IMHO...

2017-05-02 18:26 UTC, garyrussell commented
Merged as f03356ccbcdf4394e7ab3daeeb3a7362a856e5f8

2017-05-02 18:26 UTC, closed without merging