INT-4164: TCP Support Pushback and Subclassing
spring-projects/spring-integration pull request #2164
Opened 2017-05-22 21:35 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4164

Previously, it was not possible to create a subclass of `TcpNetConnection`.
This was possible for `TcpNioConnection` via `TcpNioConnectionSupport`.

Add `TcpNetConnectionSupport` and a default implementation.

Create `AbstractTcpConnectionSupport` and add support for all implementation (Net, NIO, NIO with SSL)
to support wrapping the connection's `InputStream` in a `PushBackInputStream`.

2017-05-23 18:45 UTC, artembilan requested changes
That's all from my side.

Cool stuff though!

2017-05-23 18:45 UTC, artembilan commented on spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/connection/DefaultTcpNetConnectionSupport.java
> +		private volatile InputStream original;
![never_assigned](https://cloud.githubusercontent.com/assets/1071590/26369242/1433d232-3fc2-11e7-8055-5ab32d729d9d.png)

Something has been missed in the logic of this class.

2017-05-23 18:45 UTC, artembilan commented on spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/connection/DefaultTcpNetConnectionSupport.java
> +	public static class PushBackTcpNetConnection extends TcpNetConnection {
Should this class really be `public`?

2017-05-23 18:45 UTC, artembilan commented on spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/connection/DefaultTcpNetConnectionSupport.java
> +				this.pushbackStream = new PushbackInputStream(super.inputStream(), this.pushbackBufferSize);
Aren't there any chance that `super.inputStream()` **is** already `PushbackInputStream`, so, we don't need to wrap at all?

2017-05-23 18:45 UTC, artembilan commented on spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/connection/TcpNetConnectionSupport.java
> +public interface TcpNetConnectionSupport {
`@FunctionalInterface` ?

2017-05-23 18:49 UTC, garyrussell commented on spring-integration-ip/src/main/java/org/springframework/integration/ip/tcp/connection/DefaultTcpNetConnectionSupport.java
> +				this.pushbackStream = new PushbackInputStream(super.inputStream(), this.pushbackBufferSize);
No; it's not possible - either `socket.getInputStream()` or NIO `ChannelInputStream`.

2017-05-24 18:12 UTC, artembilan approved these changes

2017-05-24 19:09 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/4991d963e8b22887a9f7ade4bf0fdea278e0c969

2017-05-24 19:09 UTC, closed without merging