INT-4269: Add Stream & Flux support for Splitter
spring-projects/spring-integration pull request #2168
Opened 2017-05-25 22:34 UTC by artembilan

JIRA: https://jira.spring.io/browse/INT-4269

* Check if `outputChannel` is `ReactiveStreamsSubscribableChannel`
to let back-pressure splitting
* Build `Flux` or `Iterator` depending in the `reactive` state
* Allow to get a size of the `iterator` if it is possible,
for example `XPathMessageSplitter`

2017-05-25 22:35 UTC, artembilan commented
TODO:
* Tests
* Docs

2017-05-30 15:43 UTC, garyrussell requested changes
That's all; cool stuff.

2017-05-30 15:43 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/splitter/AbstractMessageSplitter.java
> +	protected int obtainSizeIfPossible(Iterator<?> iterator) {
Javadocs; `@since 5.0`; "default implementation returns 0".

2017-05-30 15:43 UTC, garyrussell commented on spring-integration-xml/src/main/java/org/springframework/integration/xml/splitter/XPathMessageSplitter.java
> +		}
Perhaps a test to confirm we have a `sequenceSize` header?

2017-05-31 18:22 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/splitter/AbstractMessageSplitter.java
> +	protected int obtainSizeIfPossible(Iterator<?> iterator) {
`@since 5.0` (both) - will fix on merge.

2017-05-31 18:29 UTC, garyrussell commented
Merged as f112ecbb7e2233b37b3136a2054bf3a496087eb1

2017-05-31 18:29 UTC, closed without merging