INT-4283: MarkerFilePresentFileListFilters
spring-projects/spring-integration pull request #2170
Opened 2017-05-30 20:15 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4283

Initial commit of abstract class only. Implementations for file, (S)FTP and docs to follow after review.

2017-05-30 21:07 UTC, artembilan requested changes
That's for this round

2017-05-30 21:07 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/AbstractMarkerFilePresentFileListFilter.java
> +	 * this filter will only pass "foo.txt" if "foo.complete" is present.
M-m-m. Why do you select the extension replacing approach as default one?
Seems for me `foo.txt.complete` is much robust solution, especially when we may have `foo.exe`, `foo.jpg`, `foo.java` at the same folder.

2017-05-30 21:57 UTC, garyrussell commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/AbstractMarkerFilePresentFileListFilter.java
> +	 * this filter will only pass "foo.txt" if "foo.complete" is present.
:+1:

2017-05-31 23:34 UTC, artembilan approved these changes
That's all.
A couple minor concern and simple question.

I can merge with small polishing after your answer.

2017-05-31 23:34 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/AbstractMarkerFilePresentFileListFilter.java
> +		final Set<String> candidates = Arrays.asList(files).stream()
![image](https://cloud.githubusercontent.com/assets/1071590/26658071/d2750e9a-4635-11e7-9607-12355a4dcebf.png)

2017-05-31 23:34 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/AbstractMarkerFilePresentFileListFilter.java
> +				.map(f -> getFilename(f))
![image](https://cloud.githubusercontent.com/assets/1071590/26658080/e75c6006-4635-11e7-8aca-0753a9a8631d.png)

2017-05-31 23:34 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/FileNameFileListFilter.java
> +public interface FileNameFileListFilter<F> extends FileListFilter<F> {
Gary, any strong requirements to have this extension?
Looks like it doesn't affect `AbstractMarkerFilePresentFileListFilter` unless there might be some stranger to inject an `AbstractMarkerFilePresentFileListFilter` into the `AbstractMarkerFilePresentFileListFilter`.
Thanks

2017-05-31 23:34 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/filters/AbstractMarkerFilePresentFileListFilter.java
> +			})) {
Just nit-picking from my head. Would look better with a local variable for the `anyMatch()` result.

2017-06-02 17:30 UTC, artembilan commented
@garyrussell ,

Any problems do not answer to my concerns and let me to merge then?

Thanks

2017-06-02 18:14 UTC, garyrussell commented
I will do the requested polishing

2017-06-02 23:31 UTC, merged