INT-4033: Support SpEL in Gateway Timeouts
spring-projects/spring-integration pull request #2172
Opened 2017-06-02 18:12 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4033

Provide a mechanism to support dynamic timeouts when invoking gateway methods.

2017-06-05 20:37 UTC, artembilan requested changes
I'm fine with the fix.
Just some minor concerns are requiring an explanation.

2017-06-05 20:37 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/gateway/GatewayMethodInboundMessageMapper.java
> +				headers.putIfAbsent(GenericMessagingTemplate.DEFAULT_SEND_TIMEOUT_HEADER,
`computeIfAbsent()`? to avoid unnecessary expression evaluation.

2017-06-05 21:37 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/annotation/Gateway.java
> +	 * Specify the timeout (ms) when sending to the request channel - only applies if the
It's explained below...

>it can be a simple long value or a SpEL expression

2017-06-05 21:41 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/core/MessagingTemplate.java
> +			return doConvert(message, null);
I am not sure what you mean; see `receive()` in `MessagingGatewaySupport` - he passes in `null` too.

2017-06-05 21:46 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/core/MessagingTemplate.java
> +			return doConvert(message, null);
Yeah! I see. Never mind

2017-06-06 14:58 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/f58106ec3cda2b1b6c828d3892ba683989d07eee

2017-06-06 14:58 UTC, closed without merging