INT-4298: Add Interface HeaderPropagationAware
spring-projects/spring-integration pull request #2184
Opened 2017-06-19 18:51 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4298

Used to indicate components that can propagate headers; allows suppression.

__cherry-pick to 4.3.x__

2017-06-19 18:59 UTC, artembilan requested changes

2017-06-19 18:59 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/handler/MessageHandlerChain.java
> +		HeaderPropagationAware, CompositeMessageHandler, Lifecycle {
That's not true.
We don't propagate headers only in this case:
```
if (this.shouldCopyRequestHeaders()) {
		if (this.selectiveHeaderPropagation) {
			Map<String, Object> headersToCopy = new HashMap<String, Object>(requestHeaders);
			for (String header : this.notPropagatedHeaders) {
				headersToCopy.remove(header);
			}
			builder.copyHeadersIfAbsent(headersToCopy);
		}
```
So, or we shouldn't care about `MessageHandlerChain`  for this task (including any other should makes `shouldCopyRequestHeaders()` as `false`), or we should have some more sophisticated logic and clean the reply message from those headers independently of the component type. Pay attention to the `BridgeHandler` BTW...

2017-06-19 19:07 UTC, artembilan commented
Yeah... I understand that my comment has disappeared after your new commit, but anyway it more and more looks for me as a dead end and only the proper solution is usage of `HeaderFilter` downstream any producing component. Otherwise `Chain`, `Resequencer`, `Bridge`, `Router` and many similar who doesn't modify request message are not affected by this logic at all and in the SCSt world we always will send an output message with mentioned headers any way.
WDYT?

2017-06-19 19:12 UTC, garyrussell commented
Good point - @mbogoevici ??

2017-06-19 19:14 UTC, garyrussell commented
BTW, your comment hasn't "disappeared" you can click "show outdated" above to see it.

2017-06-19 19:17 UTC, artembilan commented
>  "show outdated" 

Great! Thank you!

Superfluous fear 😄 

I wanted to show our with @mbogoevici discussion about proxy issue in his PR in SCSt, but wasn't able to find it. Looks like some side effect of squashing or something else...

2017-06-19 20:40 UTC, mbogoevici commented
@garyrussell @artembilan 

>Otherwise Chain, Resequencer, Bridge, Router and many similar who doesn't modify request message are not affected by this logic at all and in the SCSt world we always will send an output message with mentioned headers any way.

I see the point in the general case, but from my point of view if the request message is not modified, then we don't need to worry about header propagation either. They've been in the original message, and it's OK to keep them in the reply message (which is the same as the original message). Where we need this in particular is the case when a method returns the payload only, and the handler will blindly copy headers over, resulting in inconsistent stuff - like a POJO payload with an `application/json` header which ends up throwing off the binder. 

A `HeaderFilter` downstream of a `ServiceActivator` that only filters headers that the latter shouldn't copy at all may be a workaround but is IMO cumbersome.

2017-06-20 11:52 UTC, artembilan commented
I agree with @mbogoevici . His point of view is a good middle ground. I think we good to go ahead with the solution. Only what would be great to have is some JavaDoc on the matter that `selectiveHeaderPropagation` makes effect only if `shouldCopyRequestHeaders() == true` . Some Reference Manual would be good, too.

2017-06-20 12:41 UTC, garyrussell commented
When pulling those methods to the interface, I changed the javadocs from

    if {@link #shouldCopyRequestHeaders() shouldCopyRequestHeaaders} is true.

to

    if the handler is configured to copy headers.

Since that field is not relevant on the interface.

What would you suggest instead?

I will push some docs updates.

2017-06-20 12:44 UTC, artembilan commented
> When pulling those methods up to the interface,

Doh. I see now. Sorry.
LGTM then!

A couple words in the Docs and that's it.
Thanks

2017-06-20 14:14 UTC, artembilan commented on src/reference/asciidoc/message.adoc
> +Starting with _version 4.3.10_, you can configure message handlers (that modify messages and produce output) to suppress the propagation of specific headers
Missed period. But merging anyway...

2017-06-20 14:46 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/42dd05d655d7e134242d40e5b12837f381c55de9 and cherry-picked.

2017-06-20 14:46 UTC, closed without merging