Adds a DirectoryScanner setter in AbstractInboundFileSynchronizingMessageSource
spring-projects/spring-integration pull request #2241
Opened 2017-09-18 07:55 UTC by venilnoronha

This PR adds a setter named `setScanner` in `AbstractInboundFileSynchronizingMessageSource` to specify a custom `DirectoryScanner` to be used by the `FileReadingMessageSource`.

2017-09-18 15:00 UTC, artembilan requested changes
1. Need XML support on the matter. 
2. Tests.
3. Docs.
4. Proper commit message (optional, but preferable for the future contributions; at least to avoid similar comment).

And mostly important pay attention to the logic in the `afterPropertiesSet()` around:
```
if (!this.fileSource.isUseWatchService()) {
	RecursiveDirectoryScanner directoryScanner = new RecursiveDirectoryScanner();
	directoryScanner.setFilter(filter);
	this.fileSource.setScanner(directoryScanner);
}
```

So, that looks like `useWatchService` and custom `DirectoryScanner` are mutually exclusive and we have to have some logic to let end-user to know that his/her configuration is confusing and reject the attempt to configure custom scanner and `setUseWatchService` together.

2017-09-20 23:28 UTC, venilnoronha commented
I've made the logical changes in ced2dae. However, it seems like `spring-integration-file-5.0.xsd` already contains an entry for the `scanner` attribute. Do I still need to add it somewhere else?

2017-09-20 23:44 UTC, artembilan requested changes
For the `scanner` attribute you should look into the `spring-integration-ftp-5.0.xsd` and `spring-integration-sftp-5.0.xsd`

Also, I'd be glad to see an appropriate mentioning for this new attribute in the `whats-new.adoc` and `ftp.adoc` & `sftp.adoc`.

Thank you so far!

2017-09-21 00:23 UTC, venilnoronha commented
Will do. Thanks!

2017-09-22 00:22 UTC, venilnoronha commented
I've updated the `xsd`s and tests in 7bc4957.

2017-09-25 20:52 UTC, artembilan requested changes
That's all.
Nothing critical.
I'm pretty sure this is the last review round and the next push will be exactly for merge.

Thank you for your contribution!

2017-09-25 20:52 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/remote/synchronizer/AbstractInboundFileSynchronizingMessageSource.java
> +		this.fileSource.setScanner(scanner);
The `this.fileSource.setScanner(scanner);` takes care about assert. 
We don't need this extra.

2017-09-25 20:52 UTC, artembilan commented on spring-integration-file/src/main/java/org/springframework/integration/file/remote/synchronizer/AbstractInboundFileSynchronizingMessageSource.java
> +					throw new IllegalStateException("Cannot set useWatchService and scanner at the same time");
I would prefer `Assert.state()`

2017-09-25 20:52 UTC, artembilan commented on spring-integration-ftp/src/main/resources/org/springframework/integration/ftp/config/spring-integration-ftp-5.0.xsd
> +				<xsd:attribute name="scanner" type="xsd:string">
Well, that's wrong place for this attribute.
This `base-inbound-adapter-type` is used from the `inbound-streaming-channel-adapter` as well, which doesn't have any local work by nature.

2017-09-25 20:52 UTC, artembilan commented on spring-integration-ftp/src/test/java/org/springframework/integration/ftp/config/FtpInboundChannelAdapterParserTests.java
> +		assertEquals(context.getBean("dirScanner"), fileSource.getScanner());
That's definitely about `assertSame()` because we use dependency injection, therefore our `scanner` is indeed same as a bean.

2017-09-25 20:52 UTC, artembilan commented on spring-integration-sftp/src/main/resources/org/springframework/integration/sftp/config/spring-integration-sftp-5.0.xsd
> +				<xsd:attribute name="scanner" type="xsd:string">
I think the same problem with wrong place for attribute as well.

2017-09-25 20:52 UTC, artembilan commented on src/reference/asciidoc/ftp.adoc
> +You can also provide a custom `DirectoryScanner` implementation to the `inbound-channel-adapter` via the `scanner` attribute.
Would be better to mention the version:
`Since _version 5.0_, you can also...`

2017-09-25 21:40 UTC, venilnoronha commented
Addressed your comments in 0ae5858.

2017-09-26 00:58 UTC, artembilan approved these changes

2017-09-26 01:10 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/797e5045bf2ef0563446deb4eb8a1915ec40ea8e.

Great stuff! Thank you!

2017-09-26 01:10 UTC, closed without merging

2017-09-26 01:43 UTC, venilnoronha commented
Thanks for merging!