Allow a user to set the id of the DefaultLockRepository via ctor
spring-projects/spring-integration pull request #2251
Opened 2017-09-28 20:48 UTC by cppwfs

resolves INT-4353

2017-09-28 20:57 UTC, artembilan commented
Thank you, @cppwfs , for the contribution!

Please, consider to rebase to the latest `master` to pick up the SF 5.0 GA upgrade to avoid the problem with "Bad Gateway" mentioned in Travis report.

2017-09-28 21:00 UTC, cppwfs commented
@artembilan rebased.  Thanks for the heads up!

2017-09-28 21:04 UTC, artembilan commented
Np. I have just noticed myself that my eyes are blind with all that SF goodies and, therefore, forgot to upgrade here 😄 

However according the consistence failure on CI for similar "Bad Gateway" I would say we are not guilty - something bad with our `/release` repo. Maybe too many people tries to upgrade their project to SF 5.0 GA at the same time 😉

2017-09-28 21:09 UTC, cppwfs commented
I completely agree.  Everyone wanting to play with the new toys ;-).

2017-09-28 21:09 UTC, artembilan requested changes
1. Your name to the `@author` list of affected classes
2. Update Copyright 
3. Some note about new `id` argument in the `jdbc.adoc`

Otherwise LGTM!

Feel free to reject all my concerns and I'll do the work for you during merge!

2017-09-28 21:09 UTC, artembilan commented on spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java
> +	private String id = UUID.randomUUID().toString();
No, this still has to be `final` and the default value must be populated from the default ctor.

2017-09-28 21:09 UTC, artembilan commented on spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java
> +	 * @param id the client id to be associated with locks handled by the repository.
`@since 4.3.13`

2017-09-28 21:48 UTC, cppwfs commented
Updated the PR based on your review.  Thanks for the review!!!

2017-09-28 22:29 UTC, artembilan approved these changes
That's all
Will fix on merge.
Tomorrow already...

2017-09-28 22:29 UTC, artembilan commented on spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java
> +	 * @param dataSource the {@link DataSource}used to maintain the lock repository.
Space before `used` word

2017-09-28 22:29 UTC, artembilan commented on spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/lock/DefaultLockRepository.java
> +		this.id = UUID.randomUUID().toString();
Nit-pick, but we can just delegate all the hard work to the new ctor from here

2017-09-29 14:01 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/e515a0d6432b782193c97f0d2387934ab495d3cd and cherry-picked into `4.3.x` as https://github.com/spring-projects/spring-integration/commit/b82973660bfe722dbba6d7e0899d7a14c783fc7d after resolving conflicts.

Glenn, thank you for the contribution.
Looking forward for more! 😉

2017-09-29 14:01 UTC, closed without merging