INT-4440: Support serialized UUID
spring-projects/spring-integration pull request #2404
Opened 2018-03-22 15:52 UTC by nathankurtyka

Support for serialized UUIDs (INT-4440)

2018-03-22 17:48 UTC, artembilan requested changes

2018-03-22 20:00 UTC, nathankurtyka commented
Excellent feedback!

All incorporated and pushed.

2018-03-22 22:29 UTC, artembilan requested changes
Only a couple simple concerns.

Also, please, add your name to the `@author` list and look if we need to update Copyright to the current year.

Thank you!

2018-03-22 22:29 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/support/MutableMessageHeaders.java
> +	private static UUID extractUuid(Map<String, Object> headers) {
I would call it `extractId()`.

Also, please, swap the methods: this one goes first in the class definition. Just because it is used first

2018-03-22 22:29 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/support/MutableMessageHeaders.java
> +			return (uuid instanceof String) ? UUID.fromString((String) uuid) : (UUID) uuid;
How about `UUID.nameUUIDFromBytes(byte[] name)` as well ?
There is no guarantee that we always serialize only to JSON.

Or am I paranoid? :smile:

2018-03-23 13:43 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/support/MutableMessageHeaders.java
> +		super(headers, MutableMessageHeaders.extractId(headers), MutableMessageHeaders.extractTimestamp(headers));
We don't need class name if `static` method is here as well.

Also your name for the modified test class.

I'll fix on merge.

Thank you!

2018-03-23 14:05 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/ae2aa8b6d10c20b09413776034f718de31a9915c and cherry-picked to `5.0.x`.

@nathankurtyka ,

Thank you very much for the contribution.
Looking forward for more!

A couple comments while you are still here:

1. Please, don't squash commits when push changes to the PR. It would be much easier for us to trace the progress. We are squashing during merge anyway.
2. Please, make changes in the top-level branches, not `master`. Right now you have to `reset --hard` your origin because of changes in the upstream.

2018-03-23 14:05 UTC, closed without merging

2018-03-23 14:19 UTC, nathankurtyka commented
Thank you for your patience!

Yes, my next fix will be much smoother :)