INT-4473: Support prefix bean names with flow id
spring-projects/spring-integration pull request #2450
Opened 2018-05-21 21:01 UTC by garyrussell

JIRA: https://jira.spring.io/browse/INT-4473

Previously, dynamic registration of integration flows with components configured
with the same `id` would fail with duplicate bean names.

Add `useFlowIdAsPrefix()` to the registration builder to enable the option.
Then, in the BPP, check the flag before naming the beans.

**cherry-pick to 5.0.x**

2018-05-21 21:09 UTC, artembilan requested changes
Just a couple nit-picks.

I can address on merge.

Also I believe it won't be so easy to cherry-pick since classes for the `context` have been moved a bit.

Not a big deal though. Just let me know!

2018-05-21 21:09 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/context/StandardIntegrationFlowContext.java
> +		return use == null ? false : use;
`return Boolean.TRUE.equals(use)` ?

2018-05-21 21:09 UTC, artembilan commented on src/reference/asciidoc/dsl.adoc
> +This is useful if you wish to declare multiple instances of the same flow and avoids bean name collisions if components in the flows have the same id.
s/avoids/avoid ?

2018-05-21 21:22 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/context/StandardIntegrationFlowContext.java
> +		return use == null ? false : use;
👍

2018-05-21 21:23 UTC, garyrussell commented on src/reference/asciidoc/dsl.adoc
> +This is useful if you wish to declare multiple instances of the same flow and avoids bean name collisions if components in the flows have the same id.
👍

2018-05-22 01:06 UTC, artembilan commented
Gary, I did more changes, than expected.
See polishing here: https://github.com/artembilan/spring-integration/commit/10d50d6042ffc85823160323d54fa355c645f228

2018-05-22 18:09 UTC, closed without merging