INT-2543: Relax mail host when mail-props present
spring-projects/spring-integration pull request #2702
Opened 2019-01-17 21:07 UTC by artembilan

JIRA: https://jira.spring.io/browse/INT-2543

We may have a mail server host configured in the properties and the
target session will resolve it properly from provided `javaMailProperties`.
The same applies for `username`

* Do not require `host` and `username`, when `javaMailProperties` is
provided
* Add additional factory methods into the `Mail` factory for Java DSL
* Add Java DSL sample into the `mail.adoc`

2019-01-18 19:31 UTC, artembilan commented
Repushed after rebase.

2019-01-18 20:26 UTC, garyrussell requested changes

2019-01-22 14:57 UTC, artembilan commented on src/reference/asciidoc/mail.adoc
> +
According the `MailSendingMessageHandler` implementation, it is already not our responsibility.
What we do, essentially, from the XML parser, as well as DSL spec is just a `MailSender` injection. 
It is already that component responsibility to validate for properties presence or not. 
Only the problem that iths component is out of Spring Integration scope. So, ever if that is needed we can't fix it from this PR.

On the other hand it looks like there is some `host` resolution logic in the target `javax.mail.Service.connect()`.

So, I would live this as is without any mail API abuse in our code.

2019-01-22 15:40 UTC, garyrussell commented on src/reference/asciidoc/mail.adoc
> +
Ah - this is just smtp - I didn't look closely enough; I assumed it covered inbound as well -- there are properties `mail.imap.host` and `mail.pop3.host` as well -- but this doesn't address that potential duplication.

Merging.

2019-01-22 15:56 UTC, artembilan commented on src/reference/asciidoc/mail.adoc
> +
I think that is addressed over there already.

See `Mail.pop3InboundAdapter()`. So, you are good to just have a default `Pop3MailReceiver` and provide everything else via Java Mail Properties.

Does it make sense now?

2019-01-22 16:00 UTC, garyrussell approved these changes

2019-01-22 16:00 UTC, merged