GH-2735: Add errorChannel to ScatterGatherHandler
spring-projects/spring-integration pull request #2737
Opened 2019-02-05 20:25 UTC by artembilan

Fixes spring-projects/spring-integration#2735

2019-02-06 17:19 UTC, garyrussell requested changes
That's all; but I am not sure I understand why the exception is an entry in the list.

Looking forward to docs.

2019-02-06 17:19 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/ScatterGatherSpec.java
> +	 * Specify a {@link MessageChannel} bean name for async errors processing.
`s/errors/error/` (also in param below and other javadocs).

2019-02-08 20:12 UTC, artembilan commented
>  but I am not sure I understand why the exception is an entry in the list.

Sorry, have missed your review somehow...

An exception is an item of the aggregated message because that is what my logic in the error processor does: return `MessageBuilder.withPayload(payload.getCause().getCause())`. See `@ServiceActivator(inputChannel = "scatterGatherErrorChannel")`  in the `RouterTests`. Nothing more. 
The point of the centralized `errorChannel` just because we have several requests from the single scaterrer point. So, it would be better to let all downstream errors to be settled in a single place for centralized error handling.
Of course, you still can have your own error handling in the particular sub-flow of the distribution/auction, but that is a different story, although it might finish with some compensation anyway.

Will fix your concern and explain this behavior in Docs.

Thank you!

2019-02-08 22:52 UTC, artembilan commented
Ready for the final review.

Thanks

2019-02-11 19:40 UTC, garyrussell commented
Minor doc polishing for your review: https://github.com/garyrussell/spring-integration/commit/9de4791cbf6d131f65f5600a454a6c900c849544

2019-02-11 19:42 UTC, artembilan commented
> Minor doc polishing

👍 Thank you!

2019-02-11 20:08 UTC, garyrussell commented
Merged as e8aa8618dfbaa155419500df9d1d374a1da1f9a7

2019-02-11 20:08 UTC, closed without merging