GH-2792: HEnrichSpec: Add hooks for common headers
spring-projects/spring-integration pull request #2895
Opened 2019-04-11 21:26 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/2792

2019-04-11 21:28 UTC, artembilan commented
If this is OK, I'll add other common header hooks.

It's just too much copy/paste and extra code to support in the future...

2019-04-12 14:31 UTC, artembilan commented
Ready for review.

Thanks

2019-04-12 15:18 UTC, garyrussell requested changes
I feel your pain 😄

2019-04-12 15:18 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/HeaderEnricherSpec.java
> +		return priorityFunction(expirationDateFunction, null);
copy/paste

2019-04-12 16:57 UTC, garyrussell approved these changes

2019-04-12 16:57 UTC, merged