Add `RSocketInboundGateway`; refactoring
spring-projects/spring-integration pull request #2923
Opened 2019-05-08 16:43 UTC by artembilan

* Extract an `AbstractRSocketConnector` for common client and server connectors logic
* Introduce an `IntegrationRSocketAcceptor` and `IntegrationRSocket` for the
mapping and handling logic of RSockets and messages in between
* Introduce an `IntegrationRSocketEndpoint` marker interface for Inbound Gateway mappings
* Add `RSocketInboundGateway` implementation, which is called from the
`IntegrationRSocketAcceptor` by the `IntegrationRSocketEndpoint` mapping
* Add `RSocketConnectedEvent` to emit when the client is connected to the server.
It does not make sense in Spring Integration to delegate such a logic into the
`RSocketInboundGateway`

2019-05-08 16:45 UTC, artembilan commented
This is not fully ready yet.

At least tests are needed to cover an introduced functionality.

The server inbound side and docs might be deferred into a separate PR...

Right now I just want to share what I have so far to gather any possible feedback.

Thanks

2019-05-09 13:08 UTC, garyrussell requested changes
A few comments from first review pass.

2019-05-09 13:08 UTC, garyrussell commented on spring-integration-rsocket/src/main/java/org/springframework/integration/rsocket/IntegrationRSocketAcceptor.java
> +		rsocket.setApplicationEventPublisher(this.applicationEventPublisher);
null check or no-op default implementation.

2019-05-09 13:08 UTC, garyrussell commented on spring-integration-rsocket/src/main/java/org/springframework/integration/rsocket/IntegrationRSocket.java
> +class IntegrationRSocket extends AbstractRSocket {
Oh, I see it's not a bean.

2019-05-09 13:08 UTC, garyrussell commented on spring-integration-rsocket/src/main/java/org/springframework/integration/rsocket/IntegrationRSocket.java
> +					this.applicationEventPublisher.publishEvent(
See comment at caller.

2019-05-09 13:08 UTC, garyrussell commented on spring-integration-rsocket/src/main/java/org/springframework/integration/rsocket/RSocketConnectedEvent.java
> +
I find `toString()` useful on events.

2019-05-09 22:59 UTC, artembilan commented
Pushed some further implements and implementation.
See commit comment for details.

Thanks

2019-05-10 13:47 UTC, garyrussell requested changes
Just one issue from this pass.

2019-05-10 13:47 UTC, garyrussell commented on spring-integration-rsocket/src/main/java/org/springframework/integration/rsocket/RSocketConnectedEvent.java
> +				", data=" + Arrays.toString(this.data.asByteBuffer().array()) +
I don't think rendering a `byte[]` as a bunch of ints is useful, maybe omit this (or just include the length, perhaps).

2019-05-10 17:09 UTC, artembilan commented
OK. Now I think it is very close for merging.

Pay attention, please, how `@Transformer` looks in the `RSocketInboundGatewayIntegrationTests.CommonConfig`. It is nice to have it without subscription - everything is done by the RSocket protocol.

2019-05-10 17:17 UTC, garyrussell commented on spring-integration-rsocket/src/main/java/org/springframework/integration/rsocket/RSocketConnectedEvent.java
> +				", data length=" + this.data.asByteBuffer().array().length +
This still seems to be a lot of overhead in a `toString()`.

Why do we need this `DataBuffer` in the event?

2019-05-10 21:20 UTC, merged