Encoding is now done when flag is set
spring-projects/spring-integration pull request #2929
Opened 2019-05-14 07:22 UTC by ezylot

Before we did not actually encode the URI. You can see this in the screenshot below, where the String "häuser" is not actually encoded to the correct percentage encoding.

![withoutEncode](https://user-images.githubusercontent.com/5598040/57678488-98c08000-7629-11e9-9240-b7b9d04f14fe.PNG)

When we first encode it and then call the .toUri() we can see that the "häuser" is now propoerly encoded to "h%C3%A4user"

![withEncode](https://user-images.githubusercontent.com/5598040/57678526-ae35aa00-7629-11e9-86b9-9daf0671ba4b.PNG)

2019-05-14 07:22 UTC, pivotal-issuemaster commented
@ezylot Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2929)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2929) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2019-05-14 07:23 UTC, pivotal-issuemaster commented
@ezylot Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=2929)!

2019-05-14 14:26 UTC, artembilan requested changes
Please, add your name to the `@author` list and modify, please, `HttpRequestExecutingMessageHandlerTests.testUriExpression()` to reflect your change. 
This way we definitely going to have a test coverage.

Thank you!

2019-05-14 15:15 UTC, ezylot commented
I added myself as an author and added 2 tests that check this specific problem

2019-05-14 15:29 UTC, artembilan requested changes
Please, fix Checkstyle violation

2019-05-14 15:29 UTC, artembilan commented on spring-integration-http/src/test/java/org/springframework/integration/http/outbound/HttpRequestExecutingMessageHandlerTests.java
> +import java.util.*;
No asterisk imports at all, please.

2019-05-14 17:05 UTC, ezylot commented on spring-integration-http/src/test/java/org/springframework/integration/http/outbound/HttpRequestExecutingMessageHandlerTests.java
> +import java.util.*;
Oh boy, did not check that. Fixed.

2019-05-14 17:07 UTC, artembilan approved these changes
LGTM

Will  merge after green Travis report.

2019-05-14 17:22 UTC, artembilan commented
There are still a couple Checkstyle violations:
```
[ant:checkstyle] [ERROR] /home/travis/build/spring-projects/spring-integration/spring-integration-http/src/test/java/org/springframework/integration/http/outbound/HttpRequestExecutingMessageHandlerTests.java:770:45: '}' at column 31 should be alone on a line. [RightCurly]
[ant:checkstyle] [ERROR] /home/travis/build/spring-projects/spring-integration/spring-integration-http/src/test/java/org/springframework/integration/http/outbound/HttpRequestExecutingMessageHandlerTests.java:792:45: '}' at column 31 should be alone on a line. [RightCurly]
```

2019-05-14 17:27 UTC, ezylot commented
Damnit, give me a second ^^

2019-05-16 17:24 UTC, ezylot commented
should be good to go, i think ;)

2019-05-16 17:50 UTC, merged

2019-05-16 17:50 UTC, artembilan commented
Sorry, have missed your fresh commit somehow...

Now it is merged and I'm going to cherry-pick it to `5.1.x`.

Thank you for contribution; looking forward for more!