Usage clarification of the group-timeout property.
spring-projects/spring-integration pull request #3019
Opened 2019-08-07 13:15 UTC by warbabun

Added some clarification on the usage of  the group-timeout property based on discussion here https://stackoverflow.com/questions/48230453/issue-with-spring-integration-aggregator-group-timeout-value

2019-08-07 13:15 UTC, pivotal-issuemaster commented
@warbabun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3019)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3019) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2019-08-07 13:16 UTC, pivotal-issuemaster commented
@warbabun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3019)!

2019-08-08 20:22 UTC, artembilan requested changes
Just one formatting concern.

2019-08-08 20:22 UTC, artembilan commented on src/reference/asciidoc/aggregator.adoc
> +This attribute provides a built-in time-based release strategy for the aggregator when there is a need to emit a partial result (or discard the group) if a new message does not arrive for the `Messag
Please, obey the rule *One sentence per line*: https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line

Thanks

2019-08-15 21:08 UTC, artembilan commented
Gentle ping. We can fix formatting issues on merge, but would be great to know if you agree with that or you are still going to fix it yourself.

Thanks

2019-08-20 09:01 UTC, warbabun commented
Done @artembilan

2019-08-20 14:07 UTC, merged

2019-08-20 14:07 UTC, artembilan commented
@warbabun ,

Thank you for the contribution; looking forward for more!

2019-08-20 23:05 UTC, warbabun commented
Same here!