JUnit 5 Log Level Adjuster
spring-projects/spring-integration pull request #3025
Opened 2019-08-12 19:05 UTC by garyrussell

2019-08-15 19:25 UTC, artembilan requested changes

2019-08-15 19:25 UTC, artembilan commented on spring-integration-test-support/src/main/java/org/springframework/integration/test/condition/LogLevels.java
> + * Copyright 2017-2019 the original author or authors.
I don't think `2017` should be here, even if some logic has existed before in other classes.
Also I think we need to mention how do they combine together (if any) when we have a class and method level annotations.

Would be also great to mention this new feature in Docs!

2019-08-15 19:25 UTC, artembilan commented on spring-integration-test-support/src/main/java/org/springframework/integration/test/condition/LogLevels.java
> + * Test classes annotated with this will change logging levels between tests.
Looks like we can apply this for test methods as well.
Can we have that note in this JavaDocs please, too?
Thanks

2019-08-16 14:24 UTC, artembilan commented
LGTM, but how about some “what’s new” entry and some short paragraph in the testing chapter? Thanks

2019-08-16 14:31 UTC, garyrussell commented
I don't really consider this for end user use, just for use in the framework tests; we've never documented it before.

2019-08-16 14:36 UTC, merged