GH-2890: Document a bridge for subflow starts
spring-projects/spring-integration pull request #3040
Opened 2019-08-21 14:03 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/2890

Explain in a docs why and how a `bridge` appears in the flow when we
declare a subflow for mapping

2019-08-28 20:17 UTC, garyrussell requested changes

2019-08-29 15:46 UTC, artembilan commented
Pushed some doc fix.

Thanks

2019-08-29 18:53 UTC, garyrussell approved these changes

2019-08-29 18:53 UTC, garyrussell commented
Merged as 5b43b6c7dd6069e68ce03de72770667bac4c7448 with minor polishing.

2019-08-29 18:53 UTC, closed without merging