GH-3043: Add FileHeaders.REMOTE_HOST header
spring-projects/spring-integration pull request #3044
Opened 2019-08-23 23:45 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/3043

* Populate a `FileHeaders.REMOTE_HOST` from the
`AbstractRemoteFileStreamingMessageSource` and "get"-based commands
in the `AbstractRemoteFileOutboundGateway`
* Extract the value from the a `Session.getHost()` contract
* The `AbstractInboundFileSynchronizingMessageSource` cannot be
addressed with this because the real message is already based on the
locally stored file
* Adjust some affected tests according our code style requirements

2019-08-23 23:45 UTC, artembilan commented
Will add Docs after review.
Thanks

2019-08-24 13:30 UTC, garyrussell commented
>real message is already based on the locally stored file

How about an (optional) `MetadataStore` to hold the information?

2019-08-27 20:57 UTC, garyrussell requested changes

2019-08-28 12:57 UTC, garyrussell approved these changes

2019-08-28 12:58 UTC, merged