[DO NOT MERGE YET] Add Reactive Stream chapter into docs
spring-projects/spring-integration pull request #3066
Opened 2019-09-27 15:45 UTC by artembilan

* Improve `channel.adoc`: polishing, new channels, java config
* Make `LoadBalancingStrategy` in the `DirectChannel` ctor as
`@Nullable` to reflect the real logic behind

2019-09-27 15:47 UTC, artembilan commented
Some initial documentation for reactive support in Spring Integration.

Please, tell me if the idea is OK and doc structure is clear and reasonable.

Thanks

2019-09-27 16:22 UTC, garyrussell requested changes
Structure looks fine.

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/channel.adoc
> +
A `FixedSubscriberChannel` is a `SubscribableChannel` that only supports a single `MessageHandler` subscriber that cannot be unsubscribed.

no channel interceptors *are* needed.

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/channel.adoc
> +This channel implementation is nor a `SubscribableChannel`, neither `PollableChannel`, so only `org.reactivestreams.Subscriber` instances can be used for this channel consumption honoring back-pressu
is an `org...

by reactive subscribers downstream.

neither a ``, nor a ``

can be used to consume from this channel

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/channel.adoc
> +
`s/to allow to accept/allowing receiving/`

publishers, bridging

To achieve fully reactive

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/channel.adoc
> +See <<./reactive-streams.adoc#reactive-streams,Reactive Streams Support>> for more information about an interaction with Reactive Streams.
about interaction

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/channel.adoc
> +The Java configuration variant is about a `DirectChannel` bean definition:
The equivalent Java configuration declares a `DirectChannel` `@Bean`:

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/channel.adoc
>  ----
**how** to define one

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +Spring Integration provides support for https://www.reactive-streams.org/[Reactive Streams] interaction in different place of the framework and from different aspects.
s/in difference place/in some places/

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +We will revise most of them here with appropriate links to the target chapters for details whenever necessary.
`s/revise/discuss/`

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +To recap, the Spring Integration extends the Spring programming model to support the well-known Enterprise Integration Patterns.
To recap, Spring

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +The intention of Reactive Streams implementation, such as https://projectreactor.io/[Project Reactor], is to preserve the mentioned benefits and characteristics across the whole processing graph of a
preserve these benefits

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +The ultimate goal of Reactive Streams libraries is to provide types, set of operators and support API to be a target application in transparent and smooth manner as it is possible with available prog
and supporting API for for a target application in a transparent ... as is possible ... not as imperative ... normal function chain

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +It rather divided into to phases: definition and execution which happens somewhere later during subscription to the final reactive publisher and demand for data is pushed from the bottom of the defin
It is divided .. execution, which happens some time later... publisher, and... top applying back-pressure as needed - we request as many events...

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +The reactive application looks like a `"stream"` or as we got used to in Spring Integration terms - `"stream"`.
I am not sure what this means.

2019-09-27 16:22 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +From here it may look like Spring Integration flows are really a good fit for writing Reactive Streams applications when we apply some reactive framework operators on endpoints, but in fact the probl
processed in a reactive

2019-09-30 13:23 UTC, garyrussell requested changes
Just a few minor issues.

2019-09-30 13:23 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +The simples point of interaction with Reactive Streams is a `@MessagingGateway` where we just make a return type of the gateway method as a `Mono<?>` - and the whole integration flow behind a gateway
simplest

2019-09-30 13:23 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +Similar `Mono`-reply approach is used in the framework internally for inbound gateways which are fully based on Reactive Streams compatible protocols (see <<reactive-channel-adapters>> below for more
A similar

2019-09-30 13:23 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +A reactive outbound channel adapter implementation is about initiation (or continue) a reactive stream to interaction with an external system according provided reactive API for the target protocol.
(or continuation) of a reactive

2019-09-30 13:23 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +Currently Spring Integration provides channel adapter (or gateway) implementation for <./webflux.adoc#webflux,WebFlux>> and <./rsocket.adoc#rsocket,RSocket>>.
implementations

2019-09-30 13:23 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +Also an https://github.com/spring-projects/spring-integration-extensions/tree/master/spring-integration-cassandra[Apache Cassandra Extension] provides a `MessageHandler` implementation for Cassandra
for the Cassandra reactive

2019-09-30 17:16 UTC, artembilan commented
OK. I think I'm done here.
Thank you, Gary, for review!

2019-09-30 18:29 UTC, garyrussell approved these changes

2019-09-30 18:30 UTC, garyrussell commented
Final polishing here https://github.com/garyrussell/spring-integration/commit/135a17aa9a4f89fb13309a4dd1957c90eba5e8fd for your review.

2019-09-30 18:33 UTC, artembilan commented
LGTM, Gary!
Thanks

Still much to learn for me in English! 😄

2019-09-30 18:37 UTC, garyrussell commented
Merged as ad96ca49f1d2b767320b88cb3787ee915290a160

2019-09-30 18:37 UTC, closed without merging