logout() only if connected #3123
spring-projects/spring-integration pull request #3126
Opened 2019-12-17 06:51 UTC by urajio

https://github.com/spring-projects/spring-integration/issues/3123
#3123 send logout to ftp server only if connected

2019-12-17 06:52 UTC, pivotal-issuemaster commented
@urajio Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3126)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3126) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2019-12-17 06:52 UTC, pivotal-issuemaster commented
@urajio Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3126)!

2019-12-17 14:21 UTC, artembilan requested changes
Wanted to ask about a test-case on the matter, but doesn't look it worth that.

Also, please, add your name to `@author` list in that modified `FtpSession` class.

2019-12-17 14:21 UTC, artembilan commented on spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java
> +			if (this.client.isConnected())
Checkstyle violation:
```
[ant:checkstyle] [ERROR] /home/travis/build/spring-projects/spring-integration/spring-integration-ftp/src/main/java/org/springframework/integration/ftp/session/FtpSession.java:157: 'if' construct must use '{}'s. [NeedBraces]
```

You can verify yourself locally using `gradlew clean :spring-integration-ftp:check`

2019-12-19 14:39 UTC, artembilan commented
Looks like your change has affected some test:
```
org.springframework.integration.ftp.session.SessionFactoryTests > testFtpClientInteraction() FAILED
    org.mockito.exceptions.verification.WantedButNotInvoked at SessionFactoryTests.java:79
```
Would you mind to take a look and adjust respectively?
I guess that test just doesn't have a session as connected so we don't call `logout()` according a new logic you have introduced.
I don't say that your change is wrong, but I believe the test must be fixed therefore.

Thanks

2019-12-20 11:57 UTC, urajio commented
sorry, i'm not sure how to fix this properly

2019-12-20 16:32 UTC, artembilan commented
> sorry, i'm not sure how to fix this properly

No, problem. I'll take a look today and merge your PR with an appropriate fix for the test.

2019-12-20 17:16 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/c6358a93d44f0e132f0e94d62379983adef5e4ce

@urajio ,
thank you for contribution; looking forward for more!

2019-12-20 17:16 UTC, closed without merging