Infrastructure for ReactiveMessageHandler
spring-projects/spring-integration pull request #3137
Opened 2020-01-08 22:17 UTC by artembilan

We have now a `ReactiveMongoDbStoringMessageHandler` which implements
a `ReactiveMessageHandler`, but not a `MessageHandler` for possible
deferred subscriptions to the returned Reactor type

We don't have a proper application context processing for this
new type of message handlers

* Change a  `ConsumerEndpointFactoryBean` to apply an `MH` and `RMH`
as possible types for handler
* Introduce a `ReactiveMessageHandlerAdapter` to wrap an `RMH`
into a `MH` for synchronous calls in the regular consumer endpoints
* Wrap an `RMH` into a `ReactiveMessageHandlerAdapter` for regular
endpoints and unwrap for `ReactiveStreamsConsumer`
* Add `RMH`-based ctor into `ReactiveStreamsConsumer` for target
reactive streams composition (`flatMap()` on the `RMH`)
* Remove a `DelegatingSubscriber` from the `ReactiveStreamsConsumer`
in favor of direct calls from the `doOnSubscribe()`, `doOnComplete()`
& `doOnNext()`
* Add an `onErrorContinue()` to handle per-message errors, but don't
cancel the whole source `Publisher`
* Use `Disposable` from the `subscribe()` to cancel in the `stop()`
- recommended way in Reactor
* Use `onErrorContinue()` in the `FluxMessageChannel` instead of
`try..catch` in the `doOnNext()` - for possible `onErrorStop()`
in the provided upstream `Publisher`
* Handle `RMH` in the `ServiceActivatorFactoryBean` as a direct handler
as well with wrapping into `ReactiveMessageHandlerAdapter` for return.
The `ConsumerEndpointFactoryBean` extracts an `RMH` from the adapter
for the `ReactiveStreamsConsumer` anyway
* Add XML parsing test for `ReactiveMongoDbStoringMessageHandler`
* Add `log4j-slf4j-impl` for all the test runtime since `slf4j-api`
comes as a transitive dependency from many places

2020-01-08 22:19 UTC, artembilan commented
TODO:

* Java DSL
* Annotations
* Docs

Although I can do them all in the separate PR(s).

@dturanski , this is what I meant about processing `ReactiveMessageHandler` in the flow.

Thanks

2020-01-09 16:05 UTC, artembilan commented
This one depends on #3139 . So, after merging that one I'll update here.

But I definitely would like to have this merged for upcoming release.

Thanks

2020-01-09 16:08 UTC, garyrussell commented
I will look at it today, but you might want to request a review from the Reactor team since my Reactor skills are lacking.

Minor checkstyle issue reported by Travis.

2020-01-09 16:14 UTC, artembilan commented
> Minor checkstyle issue reported by Travis.

Will fix after merging MongoDB revert.

2020-01-09 16:15 UTC, artembilan commented
@bsideup ,

any chances that you can sanctify this PR?

Thanks

2020-01-09 16:52 UTC, garyrussell requested changes
Minor issues; otherwise LGTM

2020-01-09 16:52 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/config/ConsumerEndpointFactoryBean.java
> +		Assert.state(handler instanceof MessageHandler || handler instanceof ReactiveMessageHandler,
Why ISE instead of IAE? This is a setter. `Assert.isTrue()` ?

2020-01-09 16:52 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/config/ConsumerEndpointFactoryBean.java
> +			LOGGER.warn("the advice chain cannot be applied for 'ReactiveMessageHandler'");
`s/for/to a/`

2020-01-10 22:05 UTC, artembilan commented
Please, find the changes for Java DSL in the latest commit.
Since no feedback from Reactor team, I guess we are good to go and can revise in the future if that.

Thanks

2020-01-13 13:41 UTC, merged