GH-3183: Add ReactiveRequestHandlerAdvice
spring-projects/spring-integration pull request #3197
Opened 2020-02-27 21:35 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/3183

* Introduce a `BaseReplyProducingMessageHandler` with common advices logic for target message handler
* Implement `BaseReplyProducingMessageHandler` from the `AbstractReplyProducingMessageHandler`
and newly introduced `AbstractReactiveReplyProducingMessageHandler` for message handlers with `Mono` replies
* Introduce a `ReactiveRequestHandlerAdvice` with a `BiFunction<Message<?>, Mono<?>, Publisher<?>>`
logic to apply a `Mono.transform()` operator for a returned from the handler `Mono` reply
* Make `RSocketOutboundGateway` implementing an `AbstractReactiveReplyProducingMessageHandler`
* Fix `WebFluxRequestExecutingMessageHandler` to return a `Mono.then()` instead of an explicit subscription -
it happens downstream anyway during reply producing with a proper error handling, too
* Fix `ConsumerEndpointSpec` & `ConsumerEndpointFactoryBean` to deal with an
`AbstractReactiveReplyProducingMessageHandler` as well
* Demonstrate `ReactiveRequestHandlerAdvice` in the `RSocketDslTests` - without `retry()` it fails

2020-02-27 21:38 UTC, artembilan commented
If the solution is good, I'll go ahead with WebFlux reworking.

This feature opens for us a possible to apply a `TransactionInterceptor` with a `ReactiveTransactionManager` onto our reactive-replying components. 

I may admit that this could be kinda breaking change though since that modified `RSocketOutboundGateway` is not an `AbstractReplyProducingMessageHandler` anymore...

2020-02-29 00:51 UTC, sirimamilla commented
HI @artembilan,

This will add a lot of value. As it gives a lot of scope for customization and unleashes the power of Reactive framework.

2020-03-02 19:54 UTC, garyrussell commented
>If the solution is good, I'll go ahead with WebFlux reworking.

LGTM

2020-03-03 16:03 UTC, artembilan commented
I'll come back to this after merging #3201 .
They are kinda depend and complement each other.

2020-03-03 21:08 UTC, artembilan commented
I have changed my mind: now `ReactiveRequestHandlerAdvice` checks a type of the return from the `invocation.proceed()`.
So, we don't need extra abstraction to enforce reactive behavior for target `MessageHandler`.

2020-03-05 17:07 UTC, garyrussell requested changes

2020-03-05 17:07 UTC, garyrussell commented on src/reference/asciidoc/handler-advice.adoc
> +For example when we can an HTTP request over WebFlux client, we could use bellow configuration to not wait for response more than 5 seconds:
```suggestion
For example when we can an HTTP request over WebFlux client, we could use below configuration to not wait for response more than 5 seconds:
```

2020-03-05 17:07 UTC, garyrussell commented on src/reference/asciidoc/handler-advice.adoc
> +The `message` argument is a request message for such a message handler and can be used to determine a request-scope attributes.
```suggestion
The `message` argument is the request message for the message handler and can be used to determine request-scope attributes.
```

2020-03-05 17:07 UTC, garyrussell commented on src/reference/asciidoc/handler-advice.adoc
> +The `mono` argument is a result of this message handler `handleRequestMessage()` method implementation.
```suggestion
The `mono` argument is the result of this message handler's `handleRequestMessage()` method implementation.
```

2020-03-05 18:37 UTC, garyrussell approved these changes

2020-03-05 18:37 UTC, merged