GH-3204: Add channel interceptor support to flow definition
spring-projects/spring-integration pull request #3205
Opened 2020-02-29 21:11 UTC by grubeninspekteur

Adds an `interceptor()` builder method to register one or more
channel interceptors at the current flow position.

Issue #3204

* add `interceptor(ChannelInterceptor...)` to `BaseIntegrationFlowDefinition`
* refactor to reuse interceptable channel creation from `wireTap`

2020-03-02 19:25 UTC, artembilan requested changes
Please, add your name to the `@author` list. Document a new feature in the `dsl.adoc`. And ink to that from the `whats-new.adoc`.

Thank you for contribution so far!

2020-03-02 19:25 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/BaseIntegrationFlowDefinition.java
> +	protected MessageChannel makeCurrentMessageChannelInterceptable() {
I think we need to return exactly an `InterceptableChannel` from here.
And let's call it like `currentInterceptableChannel()`! A "make" is confusing a little bit...

2020-03-02 19:25 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/BaseIntegrationFlowDefinition.java
> +	 * Adds one or more {@link ChannelInterceptor} implementations
Method JavaDocs must be imperative style: https://github.com/spring-projects/spring-framework/wiki/Code-Style#javadoc-formatting

2020-03-02 19:25 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/BaseIntegrationFlowDefinition.java
> +	public B interceptor(ChannelInterceptor... interceptorArray) {
Well, our style to make methods on this builder as verbs, in other words commands: do this or that.
Look at this as EIP-operators!

Therefore if we add this feature here, it has to be named as `intercept()`.

2020-03-05 20:13 UTC, grubeninspekteur commented
Thank you for your review! I made the requested changes and also relaxed the `Assert.notEmpty()` requirement for the interceptor array to `Assert.notNull()`.

2020-03-05 21:15 UTC, merged

2020-03-05 21:16 UTC, artembilan commented
@grubeninspekteur ,

thank you very much for the contribution; looking forward for more!