GH-3230: MMIH: Fix Pausable/Lifecycle Methods
spring-projects/spring-integration pull request #3232
Opened 2020-03-31 19:54 UTC by garyrussell

Resolves https://github.com/spring-projects/spring-integration/issues/3230

Previously, methods with the same name as `Lifecycle` methods were unconditionally ignored when no method name provided.

- Use logic similar to `ControlBusMethodFilter` to explicitly compare the candidate Method
  to those on `Paused` and `Lifecycle` and only ignore those.
- Explicitly disallow these methods when named - previously the check was only performed
  if no method name was supplied.

**Consideration for backporting:**

**Behavior change, test `lifecycleOnlyExplicitMethod()` fails on 5.2.x (method explicitly requested works).**

2020-03-31 21:09 UTC, artembilan requested changes
We probably need to document also that `Pausable` are not selected as candidates.
It is going to work only if you provide a name explicitly.

Thanks

2020-03-31 21:09 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/handler/support/MessagingMethodInvokerHelper.java
> +		return (Pausable.class.isAssignableFrom(declaringClass) || Lifecycle.class.isAssignableFrom(declaringClass))
Any chances that we log special info that `Pausable` methods are not considered as candidates?

2020-03-31 22:50 UTC, garyrussell commented
>We probably need to document also that Pausable are not selected as candidates.
It is going to work only if you provide a name explicitly.

??

If they were candidates, wouldn't they be ambiguous because they have similar signatures?

2020-04-01 14:33 UTC, artembilan requested changes
> wouldn't they be ambiguous because they have similar signatures?

No, I mean skip them from scanning at all. Exactly what we do right now.

Only concern left for this PR is some doc note to let end-users to know that those methods are not selected by default and has to be used explicitly if there is such a requirement.

2020-04-01 15:05 UTC, garyrussell commented
>Only concern left for this PR is some doc note to let end-users to know that those methods are not selected by default and has to be used explicitly if there is such a requirement.

Sorry; I still don't understand what you mean; if someone really wants to call one of the Lifecycle methods they would specify it's name. Why would it be necessary to tell them anything? Why would they expect us to select one at random?

2020-04-01 15:11 UTC, artembilan commented
> Why would they expect us to select one at random?

OK. Maybe my language is bad these days. Let me quote a reporter:

> If a service activator has methods named "start", "stop" or "isRunning", these cannot be automatically discovered by SI. The activating method must be specified explicitly.

So, I want to avoid this confusing part: if we don't specify a method name we should not expect `Pausable` methods to be selected as service-activator candidates.
I mean that we never explained such a design decision in our docs.

2020-04-01 15:19 UTC, garyrussell commented
But that's no longer the case after this fix - see the test `(String) null`.

2020-04-01 15:48 UTC, artembilan commented
Right. That's what I mean. Your `LifecycleBean` is not OK for candidates since its `start()/stop()` comes from the `Pausable/Lifecycle`.
But `LifeCycleWithCustomStart` is good because its `start()` doesn't belong to `Pausable/Lifecycle`.

I believed that the main concern of the issue that `start()` from `Lifecycle` is not selected automatically and there is no a note on the matter.

Even if current behavior is slightly different than before we should say something about `Pausable` methods auto-discovery.

I'm fine merging this as is though: no concerns from the code perspective.

2020-04-01 15:52 UTC, garyrussell commented
No; the original problem was that the user happened to create his POJO method, something like `start(Message<?>)`. And the old code ignored it. Now we don't ignore it.

>We just happened to name a method of an endpoint POJO "start". The error message was not helpful in finding the cause; If these method names are not allowed, maybe we should document it in Service Activator?

2020-04-01 16:09 UTC, artembilan commented
> And the old code ignored it. Now we don't ignore it.

OK. That's good. I fully agree with the logic we have so far.
Just wander you don't want to document this change... 😄 

That's all.

(I'll merge it is after your next reply)

P.S. Sorry for wasting your time probably for nothing...

2020-04-01 16:15 UTC, garyrussell commented
I think that adding...

"You can now name POJO methods with the same names as Lifecycle methods and they will be detected (if not ambiguous). Previously, such methods were not considered as candidates."

...is not necessary. But I will add it if you want.

2020-04-01 16:16 UTC, artembilan approved these changes
> is not necessary.

OK. Convinced.  😄 

Merging...

2020-04-01 16:17 UTC, merged

2020-04-01 16:21 UTC, artembilan commented
... and cherry-picked to `5.2.x`