GH-3247: Fix `SftpSession.exists` for error code
spring-projects/spring-integration pull request #3248
Opened 2020-04-13 18:43 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/3247

When there is no path on the SFTP server, a `ChannelSftp.SSH_FX_NO_SUCH_FILE`
error is returned in the thrown `SftpException`.

* Fix `SftpSession.exists()` to check for the `SSH_FX_NO_SUCH_FILE` to
return `false` and re-throw an exception otherwise
* Add mock test for `SftpSession.exists()`
* Add `org.mockito.AdditionalMatchers` to `checkstyle.xml` exclusions

**Cherry-pick to 5.2.x & 5.1.x**

2020-04-13 21:30 UTC, garyrussell requested changes
LGTM, but I think we need a test against the mina server, e.g. in `SftpServerOutboundTests` to verify we actually get that result from JSch.

2020-04-14 15:46 UTC, garyrussell commented
Probably not related but

```
> Task :spring-integration-sftp:test
SftpStreamingMessageSourceTests > testMaxFetchLambdaFilter FAILED
    org.springframework.messaging.MessagingException at SftpStreamingMessageSourceTests.java:160
        Caused by: org.springframework.integration.util.PoolItemNotAvailableException at SftpStreamingMessageSourceTests.java:160
            Caused by: java.lang.IllegalStateException at SftpStreamingMessageSourceTests.java:160
                Caused by: java.lang.IllegalStateException at SftpStreamingMessageSourceTests.java:160
                    Caused by: com.jcraft.jsch.JSchException at SftpStreamingMessageSourceTests.java:160
```

2020-04-14 15:47 UTC, garyrussell approved these changes

2020-04-14 17:56 UTC, artembilan commented
@garyrussell ,

It isn't related, indeed, but I can't figure out such a sporadic failure. Something is broken sometimes on Mina.
So, I have restarted the build and now it is green.

Feel free to merge!

Thanks

2020-04-14 19:26 UTC, merged

2020-04-14 19:38 UTC, garyrussell commented
Hmmm - I just cherry-picked this to 5.2 but while resolving conflicts in 5.1, I changed the exception to UncheckedIOException to avoid a breaking change. I will push that to the other branches as well.