Add `ReactiveMessageSourceProducer`
spring-projects/spring-integration pull request #3254
Opened 2020-04-22 18:33 UTC by artembilan

The `ReactiveMessageSourceProducer` wraps a provided `MessageSource`
into a `Flux` for subscription in the `subscribeToPublisher(Publisher<? extends Message<?>>)`
to make a source polling feature fully based on a reactive, on demand solution

* Introduce a `IntegrationReactiveUtils` replacing existing `MessageChannelReactiveUtils`
with more functionality
* Replace a deprecated `MessageChannelReactiveUtils` with a new `IntegrationReactiveUtils`
* Test and document the feature

2020-04-22 21:50 UTC, garyrussell requested changes
Just a few doc polishes.

2020-04-22 21:50 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +Internally it wraps a `MessageSource` into the repeatedly resubscribed `Mono` producing a `Flux<Message<?>>` to be subscribed in the `subscribeToPublisher(Publisher<? extends Message<?>>)` mention ab
mentioned

2020-04-22 21:50 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +By default it is a 1 second.
it is 1 second.

2020-04-22 21:50 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +If the `MessageSource` produces messages with a `IntegrationMessageHeaderAccessor.ACKNOWLEDGMENT_CALLBACK` information in headers, it is acknowledged (if necessary) in the `doOnSuccess()` of the orig
in the headers

if the downstream flow throws

with the failed messagee

2020-04-22 21:50 UTC, garyrussell commented on src/reference/asciidoc/reactive-streams.adoc
> +This `ReactiveMessageSourceProducer` could be used for any use-case when a polling channel adapter features should be turned into a reactive, on demand solution for any existing `MessageSource<?>` im
a polling channel adapter's features

2020-04-22 21:50 UTC, garyrussell commented on src/reference/asciidoc/whats-new.adoc
> +The `ReactiveMessageSourceProducer` is a reactive implementation of the `MessageProducerSupport` to wrap a provided `MessageSource` into the `Flux` for on demand `receive()` calls.
into a `Flux`

2020-04-23 16:16 UTC, garyrussell commented
See travis (checkstyle).

2020-04-23 18:05 UTC, garyrussell commented
```
> Task :spring-integration-core:javadoc
/home/travis/build/spring-projects/spring-integration/spring-integration-core/src/main/java/org/springframework/integration/util/IntegrationReactiveUtils.java:109: error: unknown tag: T
	 * @param <T> <T> the expected payload type.
	              ^
1 error
```

2020-04-23 18:26 UTC, artembilan commented
Pushed the fix as well.
And I have ran `check api` task locally 😉

2020-04-23 19:27 UTC, garyrussell approved these changes

2020-04-23 19:28 UTC, merged