GH-3283: HTTP Inbound handle SpEL errors
spring-projects/spring-integration pull request #3289
Opened 2020-05-22 20:30 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/3283

* Process all the request message preparation exceptions
in the provided error channel to let target application
to make a decision about an appropriate HTTP status instead of
default 500 Server Error

2020-05-26 07:54 UTC, pavden approved these changes

2020-05-27 20:31 UTC, garyrussell requested changes

2020-05-27 20:31 UTC, garyrussell commented on src/reference/asciidoc/http.adoc
> +
```suggestion
Also starting with version 5.4, an error that is encountered while preparing the request message is sent to the error channel (if provided).
A decision about throwing an appropriate exception should be done in the error flow by examining the exception.
Previously, any exceptions were simply thrown, causing an HTTP 500 server error response status, but in some cases the problem can be caused by incorrect request params, so a `ResponseStatusException` with a 4xx client error status should be thrown instead.
See `ResponseStatusException` for more information.
The `ErrorMessage` sent to this error channel contains the original exception as the payload for analysis.
```

2020-05-28 15:47 UTC, garyrussell approved these changes

2020-05-28 15:47 UTC, merged