Merge Spring Integration Kafka into Main Repo
spring-projects/spring-integration pull request #3313
Opened 2020-06-24 20:08 UTC by garyrussell

Only the last commit needs review; the others were merged from the SIK repo, to retain history.

2020-06-24 21:25 UTC, artembilan requested changes
Gary, check, please, Travis report. 
We probably don't run `checkstyleNohttp` locally.
Thanks

2020-06-24 21:31 UTC, artembilan requested changes
Also would be great to have a `What's New` entry.

Thanks

2020-06-24 21:31 UTC, artembilan commented on src/reference/asciidoc/kafka.adoc
> +Spring Integration Kafka is an extension module to the https://spring.io/projects/spring-integration[Spring Integration Project].
We probably need to revise this doc.
May be later

2020-06-24 21:55 UTC, artembilan requested changes
LGTM after NoHttp fix.

Thanks

2020-06-25 14:09 UTC, artembilan commented
Gary, any chances to fix NoHttp violations?
Btw, are you going to release new SK today?

2020-06-25 14:13 UTC, garyrussell commented
No; tomorrow.

2020-06-25 14:15 UTC, garyrussell commented
Why does the nohttp check not run with `testAll`? (which I ran).

2020-06-25 15:48 UTC, artembilan commented
Merged after some docs clean up and changing `@since` to `5.4`.

See commit history to be sure that everything from SIK is present: https://github.com/spring-projects/spring-integration/commits/master

2020-06-25 15:48 UTC, closed without merging

2020-06-25 16:02 UTC, artembilan commented
> No; tomorrow.

OK. So, I move SI release for tomorrow as well.

> Why does the nohttp check not run with testAll?

We have a condition like this:
```
if (System.getenv('TRAVIS') || System.getenv('bamboo_buildKey')) {
	apply plugin: 'io.spring.nohttp'
```

I think it is not related to `testAll`. 
It is fully OK with me to have it failed on Travis or CI afterwards.
The report is clean enough to fix it in subsequent commit.
The `NoHTTP` is not that common task when we should slow down our regular development routine.