Gateway: Propagate Error to the errorChannel
spring-projects/spring-integration pull request #3408
Opened 2020-10-21 16:29 UTC by artembilan

See SO for more info:
https://stackoverflow.com/questions/64456946/handle-exceptions-errors-other-than-messagingexception-ie-other-error-excepti

In the versions before `5.2.x` the `Error` was wrapped to the `MessagingException`
in the `AbstractRequestHandlerAdvice` and this one was handled properly
on the gateway level with its `errorChannel` configured

* Fix `MessagingGatewaySupport` to catch all the `Throwable` and try to send them as `ErrorMessage`
to the `errorChannel`.
Otherwise unwrap returned `MessagingException` and re-throw an `Error` as is to keep
the current behavior for non-handled exceptions

**Cherry-pick to 5.3.x & 5.2.x**

2020-10-21 16:51 UTC, garyrussell requested changes
Wouldn't it be safer to just fix the retry advice?

2020-10-21 16:51 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/gateway/MessagingGatewaySupport.java
> +		catch (Throwable ex) {
Needs `// NOSONAR` (catch throwable).

2020-10-21 16:51 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/gateway/MessagingGatewaySupport.java
> +				}
Needs `throw me;` to retain existing behavior of throwing error flow exceptions to caller.

It's not clear why this try/catch is here at all; this is an `Error` on the error flow, not the original flow.

2020-10-21 18:09 UTC, garyrussell approved these changes

2020-10-21 20:17 UTC, artembilan commented
>  garyrussell approved these changes

@garyrussell , do you want me to merge this PR for you?
BTW, do you agree about back-porting it?

Thanks

2020-10-21 21:12 UTC, garyrussell commented
Sure. I was waiting for travis and forgot about it.

Yes about back port.

2020-10-22 15:41 UTC, merged

2020-10-22 15:43 UTC, artembilan commented
... and cherry-picked to `5.3.x` & `5.2.x`