GH-3438: Add Build from Source into CONTRIBUTING
spring-projects/spring-integration pull request #3440
Opened 2020-12-07 18:20 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/3438

It is not clear at the moment what Java version and what build system is used
in the project from the `CONTRIBUTING.adoc`

* Add `Build from Source` section into the `CONTRIBUTING.adoc`
* Point to the `CONTRIBUTING.adoc` from the top level `README.md`
* Fix the current Java version in the `README.md`
* Mention that `Squash commits` must be avoided for subsequent commits into the PR

2020-12-07 18:21 UTC, artembilan commented
@manueljordan , FYI.

2020-12-07 19:25 UTC, garyrussell requested changes

2020-12-07 19:25 UTC, garyrussell commented on CONTRIBUTING.adoc
> +To build reference documentation (results will be in `build/reference`):
```suggestion
To build the reference documentation (results will be in `build/docs/asciidoc` and `build/docs/asciidocPdf`):
```

2020-12-07 20:04 UTC, merged

2020-12-07 23:07 UTC, manueljordan commented
Huge thanks!. 

Something interesting is about that `spring-integration` about Gradle has the `compileJava`  and `compileTestJava` blocks. It is very valuable and straightforward to indicate all about the JDK to use, but the same blocks do not exists in spring-framework for its [build.gradle](https://github.com/spring-projects/spring-framework/blob/master/build.gradle) file.

As usual, huge thanks for your efforts.

2020-12-08 02:12 UTC, artembilan commented
@manueljordan ,

Perhaps Spring Framework really relies on the default Java version. 
See Gradle docs: https://docs.gradle.org/current/userguide/java_plugin.html#sec:java-extension

> Java version compatibility to use when compiling Java source. Default value: version of the current JVM in use.

Although I see this: https://github.com/spring-projects/spring-framework/blob/master/gradle/ide.gradle.
Not sure how this works for IntelliJ IDEA though...

2020-12-08 03:44 UTC, manueljordan commented
Interesting, I assumed all the spring projects have the same 'rules' or 'conventions'

Thanks for the links. About the latter, yes it is for Eclipse. but I thought at a first glance: Why that JDK settings were not declared in an agnostic way through the `build.gradle` file from the beginning?. I hope you see my point.

Best regards ...

2020-12-08 17:11 UTC, artembilan commented
Well, I pointed you to Gradle preferences according Java version selection by default.

All Spring projects are handled by different teams and to be honest the rules what and how to use to build the specific project is fully up to that team. There is really no strict requirements: someone prefers Gradle, someone Maven. Some people use Eclipse, other - IDEA. And so on. We indeed try to generalize the code style and versions compatibility, but how project is built, tested and released is fully up to project team and really doesn't effect the other projects.

I admit that I don't face the concern you raising because I just don't contribute to all the project. The projects which are maintained by my team indeed have the same contribution process, but others where I contribute have different style because it is still managed by other team where they have Maven and Jenkins preferences. 

I think we just need to get used to the project specifics we would like to contribute rather than try to make everyone to follow some standard where there is really no such a perfect standard. So, IMHO it is better to concentrate on the code than keep forever discussion how all the project should follow the same convention for development.

2020-12-08 17:18 UTC, manueljordan commented
Totally agree about the latest paragraph, I wrote that with the best intentions and how an observation, not how a command or order.

I remember many spring projects moved from Maven to Gradle (not sure if some one is based on Maven yet)

As usual, huge thanks for all.