Subscribe to Publisher in the NullChannel
spring-projects/spring-integration pull request #3448
Opened 2020-12-21 21:32 UTC by artembilan

If a payload of the message in the flow is a `org.reactivestreams.Publisher`,
it must be subscribed somewhere downstream to initiate reactive processing.
The `NullChannel` just ignores the message altogether and therefore `Publisher`
is lost

* Check the payload of the message in the `NullChannel` for `Publisher` type
and subscribe to it
* Verify in the test and mention this logic in the docs

**Cherry-pick to 5.4.x**

2020-12-21 21:34 UTC, artembilan commented
Here is a Gitter discussion on the matter: https://gitter.im/spring-projects/spring-integration?at=5fdb3542d75db604c1959651

2020-12-22 15:23 UTC, garyrussell requested changes

2020-12-22 15:23 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/channel/NullChannel.java
> + * the reactive stream, although data is ignored in this channel.
```suggestion
 * and all {@link #send} calls will return {@code true} although no action is performed.
 * Unless the payload of a sent message is a {@link Publisher} implementation, in
 * which case the {@link Publisher#subscribe(Subscriber)} is called to initiate
 * the reactive stream, although the data is discarded by this channel.
 ```

2020-12-22 15:23 UTC, garyrussell commented on src/reference/asciidoc/channel.adoc
> +The special treatment is applied for the `org.reactivestreams.Publisher` payload of a sent message: it is subscribed in this channel immediately to initiate a reactive stream processing, although dat
```suggestion
The special treatment is applied for an `org.reactivestreams.Publisher` payload of a sent message: it is subscribed to in this channel immediately, to initiate reactive stream processing, although the data is discarded.
```

2020-12-22 17:20 UTC, merged

2020-12-22 17:21 UTC, garyrussell commented
Cherry-picked as 5ed8c11c58