GH-3450: Expose PubSub requireSubscribers option
spring-projects/spring-integration pull request #3459
Opened 2021-01-11 19:23 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/3450

* Add `PublishSubscribeChannel` ctors with the `requireSubscribers` option
with a direct delegation to the same option of underlying `BroadcastingDispatcher`
* Add factory methods to the `Channels` & `MessageChannels` to expose
this new `requireSubscribers` option
* Expose an XML `require-subscribers` attribute for the `<publish-subscribe-channel`
* Document this new `requireSubscribers` option
* Introduce a global `spring.integration.channels.error.requireSubscribers` property
for a default `errorChannel`
* Document this property and explain its default `true` in the `error-handling.adoc`
* Remove docs for `spring.integration.postProcessDynamicBeans` since it purpose was
removed since version `5.1` in favor of "always post-process behavior" as it was
always with all the `BeanPostProcessor`s

2021-01-11 19:24 UTC, artembilan commented
I will back-port it to `5.4.x` with the `requireSubscribers = false` for global `errorChannel` to avoid breaking change after review and agreement here.

Thanks

2021-01-11 22:32 UTC, garyrussell commented
It's not clear to me why this would need to be false in 5.4.x; the default error channel always has a subscriber so it would only fail if someone explicitly stops the logging hander's endpoint. I just don't see it breaking otherwise. Am I missing something?

2021-01-11 22:40 UTC, garyrussell requested changes

2021-01-11 22:40 UTC, garyrussell commented on spring-integration-core/src/main/resources/org/springframework/integration/config/spring-integration.xsd
> +								Indicates if this channel may ignore or not a message when there is no subscribers at all.
```suggestion
								Indicates if this channel may ignore or not a message when there are no subscribers.
```

2021-01-11 22:40 UTC, garyrussell commented on src/reference/asciidoc/channel.adoc
> +A `MessageDispatchingException` with a `Dispatcher has no subscribers` message is thrown when no subscribers and this option is set to `true`.
```suggestion
Starting with version 5.4.3, the `PublishSubscribeChannel` can also be configured with the `requireSubscribers` option of its `BroadcastingDispatcher` to indicate that this channel will not ignore a message silently when it has no subscribers.
A `MessageDispatchingException` with a `Dispatcher has no subscribers` message is thrown when there are no subscribers and this option is set to `true`.
```

2021-01-11 22:40 UTC, garyrussell commented on src/reference/asciidoc/error-handling.adoc
> +In this case a `MessageDispatchingException` is thrown which may lend on the client callback of the inbound channel adapter to negatively acknowledge (or roll back) an original message in the source
```suggestion
Starting with version 5.5, the default error channel is configured with the property `requireSubscribers = true` to not silently ignore messages when there are no subscribers on this channel (e.g. when application context is stopped).
In this case a `MessageDispatchingException` is thrown which may lend on the client callback of the inbound channel adapter to negatively acknowledge (or roll back) an original message in the source system for redeliveriy or other future consideration.
```

2021-01-12 14:33 UTC, artembilan commented
>  if someone explicitly stops the logging handler's endpoint

It happens automatically on application context close.
I'm really OK to back-port it as `true`, too - I'm always nervous when we lose messages. 
So, even if this breaks the current behavior when we lose messages silently, it really might be better to keep it throwing an exception by default. Fortunately with that option anyone can come back to the previous dangerous behavior.

Just my conclusion to justify your back-port concern.

So, id we are on the same page in the end, feel free to cherry-pick this commit to `5.4.x`.
Otherwise let's continue a discussion what and how to back-port.

Thanks

2021-01-12 15:05 UTC, garyrussell commented
Agreed; I just think we need a bit of doc polishing to tell them how to revert to the old behavior.

2021-01-12 18:35 UTC, garyrussell approved these changes

2021-01-12 18:35 UTC, merged

2021-01-12 18:37 UTC, garyrussell commented
Cherry-picked to 5.4.x as c880a345f7