Fix to address expectation of proper exception
spring-projects/spring-integration pull request #3611
Opened 2021-08-06 20:57 UTC by djgraff209

This fix changes the WebFluxRequestExecutingMessageHandler
The change specifically changes the contruction of the
WebClientResponseException to use the `create` factory method.

This change addresses issue #3610.

2021-08-06 20:57 UTC, pivotal-cla commented
@djgraff209 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3611)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3611) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2021-08-06 20:57 UTC, pivotal-cla commented
@djgraff209 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=3611)!

2021-08-09 13:52 UTC, artembilan requested changes
Please, fix it as we discussed on Gitter: https://gitter.im/spring-projects/spring-integration?at=611069649484630efa2a4c46.

Also consider to cover it somehow with the test. 
See https://github.com/spring-projects/spring-integration/pull/3612 for the place where you could inject the logic for your change.

Thank you!

2021-08-09 13:59 UTC, djgraff209 commented
Will attempt to provide unit test to cover later today.

2021-08-09 17:02 UTC, artembilan approved these changes
LGTM.
Merging after adding your name to `@author` list.

2021-08-09 17:15 UTC, artembilan commented
Hm.
I meant that you are OK. That's already my responsibility to clean the fix for our standards, but since you have beaten me with that new commit I merge it without my hands 😄 .

The general rule if I request changes, you have to do them. Otherwise that means everything is up to me and you are good.

So, thank you for your patience with that nasty byte buffer issue and contribution.
Looking forward for more!

2021-08-09 17:16 UTC, djgraff209 commented
Absolutely not a problem. I have been in the corporate world for many years and rigor like I'm trying to follow is meant mainly to reduce the burden on the owners.

Thanks again!

2021-08-09 17:27 UTC, merged

2021-08-09 17:41 UTC, artembilan commented
... and cherry-picked to `5.4.x` & `5.3.x`