Introduce high-level API for flows composition
spring-projects/spring-integration pull request #3624
Opened 2021-09-03 15:59 UTC by artembilan

For better end-user experience and more smooth integration logic
decomposition and distribution introduce an `IntegrationFlows.from(IntegrationFlow)`
to let to start the current flow from existing one.
On the other hand introduce an `BaseIntegrationFlowDefinition.to(IntegrationFlow)`
to let to continue the flow logic in the other existing one.
This way we can extract some templating logic into separate `IntegrationFlow` definitions
allowing at the same time to decompose a complex flow definition into logical reusable parts

2021-09-03 16:00 UTC, artembilan commented
If this is OK, I'll go ahead with docs.
Thanks

2021-09-07 19:31 UTC, garyrussell requested changes
Cool - LGTM if you want to do docs.

2021-09-07 19:31 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/IntegrationFlows.java
> +	 * @param other the {@link IntegrationFlow} to composition from.
```suggestion
	 * @param other the {@link IntegrationFlow} from which to compose.
```

2021-09-07 19:31 UTC, garyrussell commented on src/reference/asciidoc/whats-new.adoc
> +On the other side, the `IntegrationFlowDefinition` has added a `to(IntegrationFlow)` terminal operator to continue the current flow in some other existing.
```suggestion
The new `IntegrationFlows.from(IntegrationFlow)` factory method has been added to allow starting the current `IntegrationFlow` from the output of an existing flow.
In addition, the `IntegrationFlowDefinition` has added a `to(IntegrationFlow)` terminal operator to continue the current flow at the input channel of some other flow.
```

2021-09-08 16:50 UTC, garyrussell requested changes

2021-09-08 16:50 UTC, garyrussell commented on src/reference/asciidoc/dsl.adoc
> +With a `MessageChannel` abstraction as a first class citizen in Spring Integration the composition of integration flows was always assumed.
```suggestion
With the `MessageChannel` abstraction as a first class citizen in Spring Integration, the composition of integration flows was always assumed.
```

2021-09-08 16:50 UTC, garyrussell commented on src/reference/asciidoc/dsl.adoc
> +Furthermore, with a `@MessagingGateway` contract, Content Enricher components, composite endpoints like a `<chain>`, and now with `IntegrationFlow` beans (e.g. `IntegrationFlowAdapter`), it is straig
```suggestion
Furthermore, with a `@MessagingGateway` contract, Content Enricher components, composite endpoints like a `<chain>`, and now with `IntegrationFlow` beans (e.g. `IntegrationFlowAdapter`), it is straightforward enough to distribute the business logic between shorter, reusable parts.
```

2021-09-08 16:50 UTC, garyrussell commented on src/reference/asciidoc/dsl.adoc
> +Only what is needed for the final composition is a knowledge about a `MessageChannel` to send to or receive from.
```suggestion
All that is needed for the final composition is knowledge about a `MessageChannel` to send to or receive from.
```

2021-09-08 16:50 UTC, garyrussell commented on src/reference/asciidoc/dsl.adoc
> +Starting with version `5.5.4`, to abstract more from `MessageChannel` and hide implementation details from end-user, the `IntegrationFlows` introduces a `from(IntegrationFlow)` factory method to allo
```suggestion
Starting with version `5.5.4`, to abstract more from `MessageChannel` and hide implementation details from the end-user, the `IntegrationFlows` introduces the `from(IntegrationFlow)` factory method to allow starting the current `IntegrationFlow` from the output of an existing flow:
```

2021-09-08 16:50 UTC, garyrussell commented on src/reference/asciidoc/dsl.adoc
> +This way we can build flows any complexity composing them from more simpler, reusable logical blocks.
```suggestion
This way we can build flows with any complexity by composing them from simpler, reusable logical blocks.
```

2021-09-08 16:50 UTC, garyrussell commented on src/reference/asciidoc/dsl.adoc
> +For example, you may have some library of `IntegrationFlow` beans as dependency and there is just enough to have their configuration classes imported to the final project and autowired for your `Inte
```suggestion
For example, you may add a library of `IntegrationFlow` beans as a dependency and it is just enough to have their configuration classes imported to the final project and autowired for your `IntegrationFlow` definitions.
```

2021-09-08 21:14 UTC, merged