GH-3700: Fix to retry until expiration time
spring-projects/spring-integration pull request #3702
Opened 2021-12-27 16:19 UTC by Meteorkor

https://github.com/spring-projects/spring-integration/issues/3700

Fixed a case where lock acquisition attempt was abandoned earlier than expected time

If a vm uses tryLock() and another vm unlock it, it will wake up with an unlock message and try to acquire the lock, but if it fails(the other vm obtain lock), vm will return false.

2021-12-27 16:41 UTC, Meteorkor commented on spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java
> +			while (time == -1 || expiredTime >= System.currentTimeMillis()) {
Wait a minute, This code is changing.
It seems better to move while to the bottom.

2022-01-03 17:02 UTC, artembilan approved these changes
Thank you for looking into this @Meteorkor !

Pulling locally for final review...

I think that was a big mistake to introduce this pub/sub feature in a point release.
It really causes a breaking change if mixed versions of the library is used in the cluster.

I wonder how to be more careful in the future... 😢

2022-01-03 17:28 UTC, artembilan requested changes
Here is my review.

Thanks

2022-01-03 17:28 UTC, artembilan commented on spring-integration-redis/src/test/java/org/springframework/integration/redis/util/RedisLockRegistryTests.java
> +		assertThat(await).isFalse();
I changed the code here to this to optimize a performance a bit:
```
		assertThat(tryLockReady.await(10, TimeUnit.SECONDS)).isTrue();

		lock1.unlock();

		assertThat(awaitTimeout.await(1, TimeUnit.SECONDS)).isFalse();
```
Not reason to sleep if we are good to just wait for both threads to be activated.

2022-01-03 17:28 UTC, artembilan commented on spring-integration-redis/src/test/java/org/springframework/integration/redis/util/RedisLockRegistryTests.java
> +				boolean b = lock2.tryLock(3, TimeUnit.SECONDS);
Changed to this `boolean b = lock2.tryLock(10, TimeUnit.SECONDS);`.

It is really possible to fail in the test with a race condition if we don't block thread long enough. 
There is no big enough time window between 2 and 3 seconds...

2022-01-03 17:28 UTC, artembilan commented on spring-integration-redis/src/test/java/org/springframework/integration/redis/util/RedisLockRegistryTests.java
> +		final int THREAD_CNT = 3;
We use only 2 threads in the `ExecutorService`.
Would you mind to revise, please?

2022-01-03 17:28 UTC, artembilan commented on spring-integration-redis/src/test/java/org/springframework/integration/redis/util/RedisLockRegistryTests.java
> +		final ExecutorService executorService = Executors.newFixedThreadPool(THREAD_CNT);
I think the `ExecutorService` has to be `shutdown()` in the end of test method to free resources.

2022-01-03 17:28 UTC, artembilan commented on spring-integration-redis/src/main/java/org/springframework/integration/redis/util/RedisLockRegistry.java
> +			final long expiredTime = System.currentTimeMillis() + time;
I believe this line has to be a first in the method to calculate the remaining time properly.
The `obtainLock()` and `this.redisMessageListenerContainer.start()` is going to take some time anyway.
So, to be more accurate with expectation we need to `while()` already with the time what was left after those.

2022-01-04 14:16 UTC, merged

2022-01-04 14:16 UTC, artembilan commented
@Meteorkor ,

thank you again for contribution!