Issue 3501
spring-projects/spring-integration pull request #3729
Opened 2022-02-16 17:54 UTC by dmfrey

2022-02-16 18:28 UTC, artembilan requested changes

2022-02-16 18:28 UTC, artembilan commented on spring-integration-graphql/src/test/java/org/springframework/integration/graphql/outbound/GraphQlMessageHandlerTests.java
> +	static class Update {
These two last classes could be as simple as:
```
	record QueryResult(String id) {	}

	record Update(String id) { 	}
```
No need in that extra boilerplate code 😄 !

2022-02-16 20:03 UTC, artembilan requested changes

2022-02-16 20:03 UTC, artembilan commented on spring-integration-graphql/src/main/java/org/springframework/integration/graphql/outbound/GraphQlMessageHandler.java
> +	private Expression idExpression = new SupplierExpression<>(() -> null);
Let's make it more clear, so the name should be an `executionIdExpression`.
And this one can be as default expression: `new FunctionExpression<Message<?>>(message -> message.getHeaders().getId())`

2022-02-16 22:34 UTC, artembilan requested changes

2022-02-16 22:34 UTC, artembilan commented on spring-integration-graphql/src/main/java/org/springframework/integration/graphql/outbound/GraphQlMessageHandler.java
> +	public void setIdExpression(Expression executionIdExpression) {
Rename, please, the setter, too 😄

2022-02-16 22:34 UTC, artembilan commented on spring-integration-graphql/src/main/java/org/springframework/integration/graphql/outbound/GraphQlMessageHandler.java
> +			Assert.notNull(this.executionIdExpression, "'executionIdExpression' must not be null");
We don't need this because it is not null by default and null cannot pass the setter.

2022-02-17 18:24 UTC, artembilan approved these changes
Looking into this one more time locally and probably merging...

Thank you so far!

2022-02-17 20:42 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/f09c665db4291854765a536f50e3cfda1ed0369c.

@dmfrey ,

thank you very much; looking forward for more!

2022-02-17 20:42 UTC, closed without merging

2022-02-17 20:45 UTC, dmfrey commented
> Merged as [f09c665](https://github.com/spring-projects/spring-integration/commit/f09c665db4291854765a536f50e3cfda1ed0369c).
> 
> @dmfrey ,
> 
> thank you very much; looking forward for more!

No problem. Glad I could contribute.