Improve README.md file so it will have examples, explanations, and logo
spring-projects/spring-integration pull request #3798
Opened 2022-05-11 17:24 UTC by migroskub

The library's README looks pretty bad right now. The library is super maintained and well used, but from its Github page, it doesn't look like this. This PR aims at helping modernize the homepage of Spring Integration.

2022-05-11 17:38 UTC, artembilan requested changes
I won't mind to have some improvements in this file, but perhaps better to keep it short and add more links to existing resources.

Something similar to what we have so far in Spring Framework would be preferred: https://github.com/spring-projects/spring-framework

Thanks

2022-05-11 17:38 UTC, artembilan commented on README.md
> +# Installation and Getting Started
Not sure in this `Installation` word.
Plus you don't show any steps to do that.

2022-05-11 17:38 UTC, artembilan commented on README.md
> +Here is a quick teaser of a complete Spring Integration application in Java:
Doesn't look like you sample is really complete...

2022-05-11 17:52 UTC, artembilan commented
OK. I see you took it from Spring Boot README: https://github.com/spring-projects/spring-boot.

Anyway: I'd prefer to not have Spring Boot mentioning over here. It may lead to a false impression that Spring Integration requires Spring Boot.

2022-05-24 16:33 UTC, closed without merging

2022-06-03 23:36 UTC, migroskub commented
@artembilan I think you did great and improved the readme a lot. I’d improve a little the code sample you’ve attached so it’ll contain some more concrete example (so the user will get a sneak peek at the `IntegrationFlow`). And I’d also mention the asynchronous/ reactive support because people may consider their usage based on this.