GH-3826: Fix SimplePool for resizing from MAX
spring-projects/spring-integration pull request #3829
Opened 2022-06-27 15:41 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/3826

By default, the `SimplePool` is used with an `Integer.MAX_VALUE` pool size.
There is a performance degradation in the `setPoolSize()` when we try to
decrease the pool size: the `while` for `permits.tryAcquire()` is too long
close to the current `Integer.MAX_VALUE` pool size

* Revise the logic in the `setPoolSize()` to use `Semaphore.reducePermits()`
instead of the loop.
* Change the calculation for a new pool size for the current pool state:
or it is a size of a new request, or iti s equal to the `inUse.size()`.
It will be reduced on subsequent `releaseItem()` calls
* Reduce the number of `available` according a new pool size based on the `inUse`.
So, if `inUse > newPoolSize`, the `available` is cleared.
Otherewise, it is reduced to the number which would give `newPoolSize` together
with the `inUse` size

**Cherry-pick to `5.5.x`**

2022-06-27 15:43 UTC, artembilan commented
@gauravbrills,

here is some possible fix for the problem.
I'm not sure that is perfect, but still would like to share to start some discussion and gather other options.

Thanks

/CC @garyrussell

2022-06-27 17:37 UTC, garyrussell requested changes
LGTM, with change.

2022-06-27 17:37 UTC, garyrussell commented on spring-integration-core/src/main/java/org/springframework/integration/util/SimplePool.java
> +		public PoolSemaphore(int permits) {
Should be package protected (will solve checkstyle too).

2022-06-27 17:57 UTC, gauravbrills commented on spring-integration-core/src/main/java/org/springframework/integration/util/SimplePool.java
> +				else {
Guess this should help in the default init case we had

2022-06-28 17:39 UTC, artembilan commented
This has been merged as https://github.com/spring-projects/spring-integration/commit/6fe59a76aa7def82a8f38bee742e9fe5f021e511.
Thank you!

2022-06-28 17:39 UTC, closed without merging