Adds documentation on usage of the PostgresChannelMessageTableSubscriber.
spring-projects/spring-integration pull request #3890
Opened 2022-09-20 21:20 UTC by raphw

Adds a segment on the newly added class in the documentation and refers to it in the section on using databases as a queue.

2022-09-20 21:26 UTC, artembilan requested changes

2022-09-20 21:26 UTC, artembilan commented on src/reference/asciidoc/jdbc.adoc
> +mechanism which is described in a subsequent section.
Great! Can you, please, follow the rule of `One sentence per line`: https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line ?

2022-09-20 21:26 UTC, artembilan commented on src/reference/asciidoc/jdbc.adoc
> +==== PostgreSQL: receiving push notifications
Add, please, an `id` to this section, e.g. `[[postgres-notifications]]`.
And then add a new section in the `whats-new.adoc` in the `New Components` paragraph.

2022-09-20 21:26 UTC, artembilan commented on src/reference/asciidoc/jdbc.adoc
> +pub-sub mechanism based on JDBC.
I guess would be great to add a simple sample of the possible configuration of the channel and that `PostgresChannelMessageTableSubscriber` .
As `@Bean`s, of course! 😄

2022-09-20 21:51 UTC, raphw commented
Not sure how I can validate the formatting locally, but I addressed your comments.

2022-09-21 00:14 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/145edb238e1764880faa7f58d6577a91ac9b2e8f.

Thank you for prompt turn around!

2022-09-21 00:14 UTC, closed without merging