GH-3572: Migrate SFTP from `jsch` to `sshd-sftp`
spring-projects/spring-integration pull request #3892
Opened 2022-09-23 19:30 UTC by artembilan

Fixes https://github.com/spring-projects/spring-integration/issues/3572

* Rework SFTP module from the JSch API to more modern `sshd-sftp`
* Migrate generics of most API from `ChannelSftp.LsEntry` to the `SftpClient.DirEntry`
* Rework `DefaultSftpSessionFactory` to deal with an `SshClient` and create `SftpClient` wrapped to the `SftpSession`
* Implement a `ResourceKnownHostsServerKeyVerifier` to load `known-hosts` from any possible resource
* Implement an expected `SftpSession.list()` with just file name to take or pattern matching
* Remove some unused tests and their config
* Remove tests for custom `UserInfo` since we don't provide any custom out-of-the-box
* Test a new `ResourceKnownHostsServerKeyVerifier` against default `known-hosts` file

2022-09-23 19:32 UTC, artembilan commented
This is huge breaking change for SFTP module, but it is still justified with today's trends.
Plus JSch is really obsoleted and abandoned library.

2022-09-26 18:02 UTC, garyrussell requested changes
Just one minor doc change and a question/comment.

2022-09-26 18:02 UTC, garyrussell commented on src/reference/asciidoc/sftp.adoc
> +NOTE: Starting with version 6.0, an outdated JCraft JSch client has been replaced with modern https://mina.apache.org/sshd-project/index.html[Apache MINA SSHD] framework.
```suggestion
NOTE: Starting with version 6.0, the outdated JCraft JSch client has been replaced with the https://mina.apache.org/sshd-project/index.html[Apache MINA SSHD] framework.
```

2022-09-27 14:18 UTC, garyrussell approved these changes

2022-09-27 14:18 UTC, garyrussell commented
Please rebase to address what's new conflct.

2022-09-27 17:10 UTC, merged

2022-09-30 18:46 UTC, artembilan commented
A Migration Guide note: https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-5.x-to-6.0-Migration-Guide#migrate-sftp-module-from-jsch-to-apache-mina