GH-4008: Add leader and participants support
spring-projects/spring-integration pull request #4011
Opened 2023-02-06 21:30 UTC by ivan909020

Fixes spring-projects/spring-integration#4008

* change return type of LeaderInitiator.getContext() from Context to CuratorContext
* add getLeader() method to CuratorContext
* add getParticipants() to CuratorContext

2023-02-06 21:30 UTC, pivotal-cla commented
@ivan909020 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=4011)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-integration&pullRequestId=4011) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2023-02-06 21:34 UTC, pivotal-cla commented
@ivan909020 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-integration&pullRequestId=4011)!

2023-02-06 22:58 UTC, artembilan requested changes
Please, see code style of the project: https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-Framework-Code-Style.

You need to reconfigure your IDE for our editor config, so imports are ordered according to our Checkstyle requirements.

The rest looks good to me.
Will double check locally tomorrow and merge.

👍

2023-02-07 06:35 UTC, ivan909020 commented
@artembilan Fixed code style

2023-02-07 15:36 UTC, merged