Reduce instance supplier use to appease AOT
spring-projects/spring-integration pull request #8568
Opened 2023-03-02 21:10 UTC by onobc

* Remove the use of instance suppliers on bean definitions that are processed during the AOT phase.

* The remaining areas that use instance suppliers do so at runtime and do not use reflection, but instead
are passed the configured bean to register.

See https://github.com/spring-cloud/spring-cloud-stream/issues/2655

2023-03-02 21:12 UTC, onobc commented on spring-integration-core/src/main/java/org/springframework/integration/config/DefaultConfiguringBeanFactoryPostProcessor.java
> +				if (beanFactoryToUse instanceof ConfigurableListableBeanFactory listable) {
**[UNRELATED]** I agreed w/ IDEA suggestion

2023-03-02 21:13 UTC, onobc commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/context/IntegrationFlowBeanPostProcessor.java
> +				.containsValue(instance);
**[UNRELATED]** I like this new API

2023-03-02 21:30 UTC, artembilan requested changes
Thank you, Chris!
Just a couple requests to restore existing behavior in your change.
The mostly important concern that we would like to deal with existing instances in those bean definitions, but not creating new as it would be with a default class-based configuration.

2023-03-02 21:30 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/config/AbstractMethodAnnotationPostProcessor.java
> +							new RootBeanDefinition(DirectChannel.class));
Revert this one, please: it is used at runtime and not in AOT at all.

2023-03-02 21:30 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/config/InboundChannelAdapterAnnotationPostProcessor.java
> +		getDefinitionRegistry().registerBeanDefinition(messageSourceBeanName, beanDefinition);
Same here: not AOT, but rather runtime stuff.

2023-03-02 21:30 UTC, artembilan commented on spring-integration-core/src/main/java/org/springframework/integration/dsl/context/IntegrationFlowBeanPostProcessor.java
> +							BeanDefinitionBuilder.genericBeanDefinition(instance.getClass())
Revert this one. You essentially making a bug here: a bean definition is going to be based on a new instance of the class, but not provided one as intention.
More over this class does its stuff at runtime, so the change is redundant.

2023-03-03 00:00 UTC, merged

2023-03-03 00:01 UTC, artembilan commented
... and cherry-picked to `6.0.x`