GH-8609: Fix bug that cannot applied correctly TcpConnectorInterceptor
spring-projects/spring-integration pull request #8610
Opened 2023-05-04 01:41 UTC by kazuki43zoo

Fixes spring-projects/spring-integration#8609

* add getLastWrapper() in TcpConnectionSupport
* change to passed the instance that geted via getLastWrapper() instead of self instance to TcpSender#addNewConnection

2023-05-04 13:59 UTC, artembilan requested changes
I wonder what is wrong with my suggestion to fix `TcpConnectionInterceptorSupport`: https://github.com/spring-projects/spring-integration/issues/8609#issuecomment-1533480685.

The test looks OK and I believe the outcome will be exactly the same with my fix.

2023-05-04 14:48 UTC, artembilan commented
Yeah... It would be better to not have any wrapping at all, but rather just a chain of interceptors injected into a `Connection`.
But that's fully different story.

Let's listener what @garyrussell has in his mind on the matter!
He is an author of this TCP/IP framework, so better to make the final decision counting on his opinion.

Thank you for the contribution anyway!

2023-05-04 17:16 UTC, garyrussell commented
>I thought it would be better to pass the last wrapped connection to all interceptors, what do you think?

My intuition is that an interceptor in the chain should only reference the next in the chain, not the outermost one.

So I prefer @artembilan 's approach.

2023-05-04 20:56 UTC, kazuki43zoo commented
@garyrussell @artembilan 
Thanks for your comment!! I will change the code by @artembilan 's approach!!

2023-05-04 21:17 UTC, kazuki43zoo commented
@garyrussell @artembilan 
I've changed the code by @artembilan 's approach, please review again when you have time! Thanks!

2023-05-05 13:29 UTC, artembilan approved these changes

2023-05-05 13:32 UTC, merged

2023-05-05 13:35 UTC, artembilan commented
... and cherry-picked to `6.0.x` & `5.5.x`.

@kazuki43zoo ,
thank you for contribution; looking forward for more!