GH-8678: Make Buffer Overflow Strategy Configurable in IntegrationWebSocketContainer
spring-projects/spring-integration pull request #8679
Opened 2023-07-16 17:34 UTC by ColoredCarrot

Implement #8678: Make the send buffer overflow strategy configurable in IntegrationWebSocketContainer.

Adds a simple setter that is the missing analogue to `setSendTimeLimit` and `setSendBufferSizeLimit`.

2023-07-17 14:01 UTC, artembilan requested changes
Thank you for the contribution.

A couple more comments to whatever I have already reviewed:
1. Any chances to have a simple unit test to new property is propagated properly to the decorated `WebSocketSession`. We can verify that via `TestWebSocketListener` in the `ClientWebSocketContainerTests`.
2. Add your name to the `@author` list of the affected classes.

2023-07-17 19:35 UTC, ColoredCarrot commented on spring-integration-websocket/src/main/java/org/springframework/integration/websocket/IntegrationWebSocketContainer.java
> +	public static final ConcurrentWebSocketSessionDecorator.OverflowStrategy DEFAULT_SEND_BUFFER_OVERFLOW_STRATEGY =
I considered the latter approach as well. I thought that having the default be explicit in this class, in addition to `ConcurrentWebSocketSessionDecorator`, would relieve users of having to open up `ConcurrentWebSocketSessionDecorator` to see the default.
We could mention that `TERMINATE` is the default in the Javadoc, but I feel like that would more than likely not get updated if the default is ever changed in `ConcurrentWebSocketSessionDecorator`. Thoughts?

2023-07-17 19:51 UTC, artembilan commented on spring-integration-websocket/src/main/java/org/springframework/integration/websocket/IntegrationWebSocketContainer.java
> +	public static final ConcurrentWebSocketSessionDecorator.OverflowStrategy DEFAULT_SEND_BUFFER_OVERFLOW_STRATEGY =
Well, to have a single place of truth, I'd prefer a `@see ConcurrentWebSocketSessionDecorator` in our new setter for this strategy.
Right, user would need to look there for more info, but then we would not not to worry about breaking change ever.

2023-07-17 20:04 UTC, ColoredCarrot commented
Thank you for the detailed review & comments!

About the unit test: Unlike `sendTimeLimit` and `bufferSizeLimit`, `ConcurrentWebSocketSessionDecorator`'s `overflowStrategy` has no getter (and is private). This seems like an oversight. Since `ConcurrentWebSocketSessionDecorator` isn't part of Spring Integration, we (probably?) can't fix that as part of this ticket.

In the meantime, the only way I can see to implement this test is by testing the actual behavior (I'm assuming using reflection to get the field value is out of the question). That would essentially duplicate [this test case](https://github.com/spring-projects/spring-framework/blob/main/spring-websocket/src/test/java/org/springframework/web/socket/handler/ConcurrentWebSocketSessionDecoratorTests.java#L133) of Spring WebSocket.
Definitely possible; is that within the scope, or should we await the getter?

2023-07-17 20:13 UTC, ColoredCarrot commented on spring-integration-websocket/src/main/java/org/springframework/integration/websocket/IntegrationWebSocketContainer.java
> +	public static final ConcurrentWebSocketSessionDecorator.OverflowStrategy DEFAULT_SEND_BUFFER_OVERFLOW_STRATEGY =
Fair enough, I'll get that implemented :)

2023-07-17 20:13 UTC, artembilan commented
> or should we await the getter?

No, we should not.

See the mentioned `ClientWebSocketContainerTests` and its `TestWebSocketListener` with an `afterSessionStarted()` impl.
That's where that `ConcurrentWebSocketSessionDecorator` is propagated.
To get access to that `private ConcurrentWebSocketSessionDecorator.overflowStrategy` property we just can use our `TestUtils.getPropertyValue()` API which indeed is based on reflection anyway, but much easier to use.

2023-07-17 20:25 UTC, ColoredCarrot commented
Right, I just wasn't aware that extracting private values like that was common practice. Won't be an issue then, thanks for the heads up.

2023-07-18 14:53 UTC, artembilan approved these changes
I'm merging with with some refactoring to be able to back-port this down to `5.5.x` where we cannot use `record` yet.

2023-07-18 15:13 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/be53593af9fa745e5dc563abca2cd003173269c1.

2023-07-18 15:13 UTC, closed without merging