GH-8681: Websocket: Expose send buffer overflow strategy in XML config
spring-projects/spring-integration pull request #8682
Opened 2023-07-18 19:41 UTC by ColoredCarrot

Implement #8681: Add an XML configuration element for the send buffer overflow strategy (`Client`- and `ServerWebSocketContainer`)

2023-07-19 17:50 UTC, artembilan requested changes
Looks good!

Can you now, please, consider to add a new section in the `whats-new.adoc`  like:
```
[[x6.2-websockets]]
=== WebSockets Changes
```

And mention this new option with the link in the end to the `web-sockets.adoc`.

Thank you!

2023-07-20 20:06 UTC, ColoredCarrot commented
Sure thing, though I won't be able to get to it for a day or two

2023-07-20 20:07 UTC, artembilan commented
That's OK, no rush: we have like a month until next milestone.

Thank you for consider the fix!

2023-07-24 15:03 UTC, merged

2023-07-24 15:04 UTC, artembilan commented
@ColoredCarrot ,

Thank you for contribution!

If you are looking forward for more of them, feel free to pick any opened issue or consider to add Java DSL for this WebSocket module.

2023-07-24 17:29 UTC, ColoredCarrot commented
Thanks @artembilan :)
I'm doing my bachelor's thesis at the moment, so not too much free time. But I've really enjoyed contributing, so I'll definitely look for more when I can!