GH-8711: Allowing SKIP LOCKED in MySqlChannelMessageStoreQueryProvider and PostgresChannelMessageStoreQueryProvider
spring-projects/spring-integration pull request #8719
Opened 2023-08-30 22:46 UTC by AdamaSorho

#8711 

- Added `useSkipLocked` property, `setUseSkipLocked(boolean)` and `getUseSkipLocked()` methods in `AbstractChannelMessageStoreQueryProvider`. I added `setUseSkipLocked(boolean)` in case there are some MySql and PostgresSql version which not support `SKIP LOCKED`. Let me know if we don't need it.
- Added `addSkipLocked(query)` and updated all methods in `PostgresChannelMessageStoreQueryProvider` and `MySqlChannelMessageStoreQueryProvider` classes.

2023-08-30 22:59 UTC, artembilan requested changes
Thank you for quick turn around! 
I don’t think we need that configuration option. This type of classes are very simple to override . Plus it is really recommended to use the latest DBs. 

Now, imaging there are other hints. Should we expose props for them as well?  I just don’t see a reason to overcomplicate the logic when plain string can be easily used.

2023-08-31 02:55 UTC, AdamaSorho commented
The build has failed for `:spring-integration-file:test`, but I can't see the error. I've tried to test locally with `./gradlew clean :spring-integration-file:check`, I'm getting an error. See attached screenshot. 
<img width="1256" alt="testOS spring-integration-file test case failed" src="https://github.com/spring-projects/spring-integration/assets/37632838/6a1878aa-c10b-4121-9ddc-17e3169eb0ac">

Did I miss something to test `:spring-integration-file`?

Note: `spring-integration-jdbc` tests passed successfully.

2023-08-31 15:01 UTC, artembilan commented
I re-ran your PR build because that test has noting to do with your changes and it really fails sporadically, especially on Linux where file system events are a bit slower to be emitted.

2023-08-31 15:25 UTC, artembilan requested changes
Now it fails like this:
```
 PostgresChannelMessageTableSubscriberTests > testMessagesDispatchedInTransaction() FAILED
    org.opentest4j.AssertionFailedError at PostgresChannelMessageTableSubscriberTests.java:189
```
And this is probably related to the changes in your PR...

2023-08-31 15:45 UTC, artembilan requested changes
It looks like we need to call `postgresChannelMessageTableSubscriber.stop()` in that test just after `assertThat(latch.await(10, TimeUnit.SECONDS)).isTrue();`.
This way that `PostgresChannelMessageTableSubscriber` won't poll DB any more making those records we try to verify next locked.

2023-08-31 16:40 UTC, artembilan approved these changes
Merging after some clean up locally.

2023-08-31 16:59 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/571ed20905059c2c52f22e74e305f69320e244ad.

Forgot to mention before, although I believe we have that in the [Contribution Guidelines](https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc):

1. First commit message becomes a PR description
2. The head line of the first commit must be not longer than 50 symbols
3. The next line must be a link to the issue with a `Fixed` keyword. This way the issue on GitHub going to be closed automatically.
4. The rest of text in this an subsequent commit messages must describe not just what has been changes, but also why.

See that Chris Beam's article in the end: https://cbea.ms/git-commit/

If you would like to contribute more, I have this pretty straightforward task for you.
Deprecate that `AbstractChannelMessageStoreQueryProvider` in favor of `default` method impls in the `ChannelMessageStoreQueryProvider` interface.
And remove its usage from those impls since the interface will carry on all the required default behavior.
Not need in the issue - just open PR and we will go from there.

Thank you for your great effort!

2023-08-31 16:59 UTC, closed without merging

2023-08-31 17:10 UTC, AdamaSorho commented
Okay, thank you for these notes.

I'll open a PR.