Deprecate AbstractChannelMessageStoreQueryProvider
spring-projects/spring-integration pull request #8721
Opened 2023-08-31 21:38 UTC by AdamaSorho

Deprecate that `AbstractChannelMessageStoreQueryProvider` in favor of default method impls in the `ChannelMessageStoreQueryProvider` interface.

Take advantage of default interface methods.

2023-08-31 22:26 UTC, artembilan requested changes
Please, also find this deprecated class in the `message-store.adoc` and fix respective sentences to use an interface instead.

2023-08-31 22:26 UTC, artembilan commented on spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/channel/AbstractChannelMessageStoreQueryProvider.java
> +@Deprecated
Please, also add a `@deprecated in favor of default methods in ChannelMessageStoreQueryProvider` into a JavaDoc of this class after `@since`

2023-08-31 22:26 UTC, artembilan commented on spring-integration-jdbc/src/main/java/org/springframework/integration/jdbc/store/channel/AbstractChannelMessageStoreQueryProvider.java
>  	public String getCountAllMessagesInGroupQuery() {
Since all methods have been moved to the interface, there is no need to keep them in this class any more.

2023-09-01 14:11 UTC, artembilan commented
```
PostgresChannelMessageTableSubscriberTests > testMessagesDispatchedInTransaction() FAILED
    org.opentest4j.AssertionFailedError at PostgresChannelMessageTableSubscriberTests.java:193
```
So, there is still a race condition between transaction in the `PostgresSubscribableChannel` and our queries in the this test.
I think I see what is going on and that is indeed a bug.
We have there this condition `while (dispatchedMessage.isPresent())` which is never false if we rollback transaction in this loop.
Therefore even if we stop a publisher it doesn't mean that we stop this loop.
And even worth: when we fully unsubscribed from this channel, the loop doesn't stop when TX is rolled back.

I'm going to open PR with a fix: nothing to do for your one.
This will be merged shortly.

Thank you!

2023-09-01 14:30 UTC, artembilan commented
Here is the fix if you are interested: https://github.com/spring-projects/spring-integration/pull/8723

2023-09-01 14:32 UTC, merged

2023-09-01 14:55 UTC, AdamaSorho commented
Ok perfect! Thank you

2023-09-01 15:21 UTC, artembilan commented
See also a Migration Guide note: https://github.com/spring-projects/spring-integration/wiki/Spring-Integration-6.1-to-6.2-Migration-Guide#deprecation-of-the-abstractchannelmessagestorequeryprovider