GH-8713: Support custom SftpClient
spring-projects/spring-integration pull request #8736
Opened 2023-09-15 04:05 UTC by AdamaSorho

Fixes #8713 

Introduce `protected createSftpClient(...)` to support custom sftpClient. It can be overridden by the end-user

2023-09-15 14:09 UTC, artembilan requested changes
This change also requires mentioning in the `session-factory.adoc`  to explain what this new method is about. Probably with a sample how to call `ChannelSubsystem.addRequestHandler()` in the custom `SftpClient`.

Of course, a new `[[x6.2-sftp-changes]]` is needed to be added to the `whats-new.adoc` as well.

I also mentioned before a convenient way what to do with the fist commit message in the PR: https://github.com/spring-projects/spring-integration/blob/main/CONTRIBUTING.adoc#provide-a-link-to-the-github-issue-in-the-associated-pull-request. What I mean that you just shape that commit message they way that you would not need to modify a PR description and that commit message will appear in the history with all the traceable information.

Thanks

2023-09-15 15:45 UTC, AdamaSorho commented
Oh  Sorry, I got it now.

Thanks

2023-09-15 23:29 UTC, AdamaSorho commented
I am trying to add a sample of how to call `ChannelSubsystem.addRequestHandler()` with this issue use case, but I am having some hard time getting it.  I don't know how to get an instance of `RequestHandler<Channel>` for `keepalive` request.

2023-09-18 14:16 UTC, artembilan commented
There is no out-of-the-box `RequestHandler<Channel>` instance for `keepalive` request.

So, our ample in the doc must be as simple as this:
```
		@Override
		protected ChannelSubsystem createSftpChannelSubsystem(ClientSession clientSession) {
			ChannelSubsystem sftpChannelSubsystem = super.createSftpChannelSubsystem(clientSession);
			sftpChannelSubsystem.addRequestHandler((channel, request, wantReply, buffer) -> ...);
			return sftpChannelSubsystem;
		}
```

and we say that custom `SftpClient` can override the `createSftpChannelSubsystem()` method to add, for example, some custom `RequestHandler` for SFTP sub-system requests and replies.

2023-09-18 16:27 UTC, artembilan requested changes

2023-09-18 16:27 UTC, artembilan commented on src/reference/antora/modules/ROOT/pages/sftp/session-factory.adoc
> +See a sample below of how to override `createSftpChannelSubsystem()` method in your custom `SftpClient` to add, for example, some custom RequestHandler for SFTP sub-system requests and replies:
```suggestion
See a sample below of how to override `createSftpChannelSubsystem()` method in your custom `SftpClient` to add, for example, some custom `RequestHandler` for SFTP sub-system requests and replies:
```

2023-09-18 16:27 UTC, artembilan commented on src/reference/antora/modules/ROOT/pages/sftp/session-factory.adoc
> +NOTE: `createSftpClient(...)` can be overridden to create your custom `SftpClient` which will be used by `getSession()`.
We don't need this sentence: it is just duplication of the first one in this paragraph.

2023-09-18 16:27 UTC, artembilan commented on spring-integration-sftp/src/main/java/org/springframework/integration/sftp/session/DefaultSftpSessionFactory.java
> +	 * This method allows the end-user to provide a custom {@link SftpClient}
I don't think there is a reason to say on a method that it is a method.
Why just not: `Can be overridden to provide a custom`.
To be honest: I try to pursue "personless" docs as much as possible.
So, something like `you`, `we`, `end-user` are not appropriate words in our docs.

More over the `end-user` in this doc is misleading: the class extension and method override actions are indeed not for users of the compiled programs.

2023-09-18 20:42 UTC, artembilan commented
Merged as https://github.com/spring-projects/spring-integration/commit/10e79ba618e10f39b15631503b0b3732e328a32b after some clean up.
Back-ported to `6.1.x` as https://github.com/spring-projects/spring-integration/commit/78b09ed6102f1ca1a203e3a5d75220334257427e after some conflict resolutions.

Thank you for contribution!

2023-09-18 20:42 UTC, closed without merging